### ISSUE TITLE
Subpixel Mode 3 uses excessive memory

### ISSUE THREAD

**Issue by zmoratto** [NeoGeographyToolkit/StereoPipeline#1]
Processing CTX pairs causes errors for user in OpenSUSE 64 bit and in OSX. Error in OSX says:

<pre>
@ row 450: average pixel took 113.702 over 421789 pixels
@ row 650: average pixel took 107.02 over 574511 pixels
/isis3/isis/bin/stereo: line 28: 3005 Bus error "${LIBEXEC}/$(basename $0)" $*
</pre>

My guess is that Alex's debug code is still deeply embedded and is the cause of this excessive use of memory.

**Comment by oleg-alexandrov** [comment]
Nobody's ever going to look at this. In the meantime subpixel-mode 3 has been coopted by our faster implementation of subpixel-mode 2 (no more EM), and now one should use subpixel-mode 5 to reach the old functionality mentioned in this issue. The doc marks this mode as experimental. I am reluctant to wipe this code altogether, but for all practical purposes this is not something the user would ever be concerned with.
