### ISSUE TITLE
Study the accuracy of our RPC model generation in dg_mosaic

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#114]
Each DG image/camera has both a rigorous linescan model and an approximate RPC model, we use the latter for map-projection.

When we mosaic DG images with dg_mosaic, we have to create a new combined RPC model for it. When there is only one image to mosaic, David compared the result of doing triangulation with the original linescan model vs the original RPC model, and then the result of the original linescan model vs our generated RPC model. The height error for the obtained DEM grows from 3 to 6 meters. 

I would argue that this is not bad at all, as our RPC model is meant to be used for map-projection with a very coarse DEM (rather for standalone stereo), and map-projection is an intermediate step to help with image alignment and which is always undone before the rigorous triangulation with the linescan camera. 

Nevertheless, it may be worth investigating why the original RPC model performs somewhat better.

**Comment by ScottMcMichael** [comment]
We have made some improvements to the RPC approximation which should address this issue.
