### ISSUE TITLE
Reduce size of disparities

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#121]
Currently disparities are written with 3 bands, with the third being just a mask. One could instead write just the first two bands, and setting invalid values there to a no-data value (e.g., the smallest float, -1.0e+38, as we'd never expect this value to be a valid disparity).

This should reduce the storage quite a bit, but it is not clear by how much since the third band is effectively binary and LZW may be clever about compressing it. Currently RD.tif and F.tif can be more than half of the size of PC.tif, and sometimes almost as large.

**Comment by oleg-alexandrov** [comment]
It would be too much work to change the way disparities are saved. In parallel_stereo there's the option --keep-only now, which can consolidate the disparities from all subdirectories and then wipe all intermediate ones (only F.tif is needed usually). This can help managing storage. https://stereopipeline.readthedocs.io/en/latest/tools/parallel_stereo.html

**Comment by dshean** [comment]
I'm less concerned about disk storage (compression should reduce significantly), but wondering about overhead for various steps to read, store in memory, modify and write the unnecessary 3rd band in D/RD/F.tif and 4th band in PC.tif?
I agree it's not critical, and probably requires a fair amount of work, but this could potentially be a "long-term maintenance" item to modernize the legacy VW file structures.

**Comment by oleg-alexandrov** [comment]
The time and memory needed to compute a disparity, especially with a large search range, is much larger than the one needed to simply read it and process it. That follows from the observation that stereo_corr is much slower and use a lot more RAM than stereo_tri, even though both operate on disparities.
