### ISSUE TITLE
Camera calibration tool

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#127]
Given that we will have SfM functionality soon, it may make sense to have a little tool that can calibrate a camera. Such functionality already exists in OpenCV, which we now link to, so it should be as simple as taking OpenCV's sample executable and bundling it with our tools (with documentation), and give our camera model generating tool the ability to ingest such an XML distortion file. 

This is  not a high priority item, but could be nice and little work to get done.

**Comment by ScottMcMichael** [comment]
The camera_calibrate tool has been added.
