### ISSUE TITLE
 "Error: ErrorMnimizer: no point to minimize".  

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#128]
user said: I'm encountering an error using pc_align on non-asp DEMs.  In this case, I am aligning a 2m DEM to a specific previously aligned point cloud, and I get an error while the algorithm is filtering outliers: "Error: ErrorMnimizer: no point to minimize".  

The problem indeed shows up when there is no overlap in pc_align among the clouds. Very easy to reproduce. And should be very easy to put a fix to catch that libpointmatcher error and replace it with a more-user friendly message.

**Comment by ScottMcMichael** [comment]
Added in 1c80f23e791ff6e5fcaf417466fd879ef4b3e558
