### ISSUE TITLE
Scaling option in pc_align

### ISSUE THREAD

**Issue by ScottMcMichael** [NeoGeographyToolkit/StereoPipeline#130]
Having pc_align being able to solve for scale differences may be critical for handling KH9 data.  There is some existing work in this area here:  https://github.com/ethz-asl/libpointmatcher/issues/141

**Comment by oleg-alexandrov** [comment]
Good to know. We'll get to it I guess when work on KH9 starts.

**Comment by oleg-alexandrov** [comment]
I added this in. Almost all the work went into merging the above contrib properly into libpointmatcher, with unit tests and official blessing from its developer. It works only for point-to-point ICP, and only when the scale and the rotation/translation transform is not too different from the identity.
