### ISSUE TITLE
Improvments in solving our tools for solving for cameras from scratch

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#131]
ASP has gained very good support for handling imagery with incomplete, inaccurate, and missing camera metadata, including solving for camera poses, dealing with distortion, scale changes, transforms of camera sets to real world coordinates from abstract coordinates, etc. (Thanks, Scott!)

Particularly, a lot o testing has been done with IceBridge, and a tutorial was added to for that purpose. 

More polishing will need to be done. Here are some highlights, noted by Scott.
- Solve for/optimize intrinsic parameters.  Currently the user has to provide them and they are not changed.
- Speed up Ceres bundle_adjust.  It starts to slow down as you add more cameras and I bet some optimization/tweaking would improve this a lot.
- Speed up Theia by having it use the estimated camera positions and restricting which image pairs it tries to match.
- Export Theia's IP detection results to ASP so we don't have to duplicate this work.
- Maybe some scripts to help assemble a large DEM for IceBridge once the cameras have been solved for.

**Comment by ScottMcMichael** [comment]
THEIA now as improved support for solving for intrinsic parameters:  https://github.com/sweeneychris/TheiaSfM/commit/64c7ac1452f8c2fc8bcb7672bfeb3707ef21174f

**Comment by ScottMcMichael** [comment]
THEIA has added support for generic camera models so we should now be able to match the same camera types we use in ASP in THEIA, allowing us to better model the camera and solve for intrinsic parameters.

**Comment by oleg-alexandrov** [comment]
This will be awesome.

**Comment by oleg-alexandrov** [comment]
There's been quite some work since then when it comes to solving for cameras and intrinsics:

https://stereopipeline.readthedocs.io/en/latest/bundle_adjustment.html#floating-intrinsics-and-using-a-lidar-or-dem-ground-truth

https://stereopipeline.readthedocs.io/en/latest/tools/camera_solve.html

https://stereopipeline.readthedocs.io/en/latest/tools/rig_calibrator.html

There was also quite some validation for IceBridge and historical image processing (KH).
