### ISSUE TITLE
Improve the shipped tests

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#132]
Modify the tests shipped with ASP (when the user types 'make check') to make them much faster, make sure all of them run, and have them run each night as part of the regular build/test process.

**Comment by ScottMcMichael** [comment]
I made a pass through all the tests to make them run and improve the speed.  They are much faster than before but still probably too slow to run nightly.

**Comment by oleg-alexandrov** [comment]
Nowadays all features are being tested using the nightly regression that runs over very diverse (an ever-increasing) datasets. This seems to be more convenient than unit tests for each function.
