### ISSUE TITLE
Improve stereo correlation

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#134]
Research ideas for how to revamp our stereo correlation algorithm. Our current approach is getting old and may not be competitive anymore.

**Comment by oleg-alexandrov** [comment]
- Look at the SETSM paper, which uses a different approach from us. It solves the DEM using camera and  image information simultaneously, rather than doing camera-agnostic correlation followed by camera-based triangulation.

 - Look at DAISY: http://cvlab.epfl.ch/software/daisy

 - Study MicMac (https://github.com/archeos/micmac-archeos). Under a BSD-like license.

 - Other publications/ideas.

**Comment by oleg-alexandrov** [comment]
- Adaptive window size for correlation?

**Comment by ScottMcMichael** [comment]
Closing this since we added SGM.
