### ISSUE TITLE
Collect together interest point matching codes

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#137]
This was mostly done, but some more scattered ip matching logic is still present in tif_mosaic, lronacjitreg, and maybe other places.

**Comment by ScottMcMichael** [comment]
Looked into lronacjitreg and the logic is different enough that it can stand as it is.

**Comment by oleg-alexandrov** [comment]
I factored out some low-level ip-finding and matching chunks of code in both tif_mosaic and lronacjitreg and replaced them with a single call to detect_match_ip(). The results change very slightly and in very acceptable ways only in tif_mosaic, not in lronacjitreg. Will make future maintenance easier. 

The entire ip matching logic should at some point just be moved to VisionWorkbench.
