### ISSUE TITLE
paths in camera_calibrate and in camera_solve

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#140]
Both of these python scripts have lines of the form:

        os.chdir(libexecpath)

the problem is that unless ASP is packaged, libexecpath does not exist and this call fails. And it looks clumsy to cd to a tools dir to run something form there, instead of doing it from the current data dir without any cd. 

Other python tools avoid this fragile trick by invoking the function libexec_path(prog) from asp_system_utils.py which returns the correct path to any given ASP  tool regardless of whether ASP is in packaged mode or just the devel version.

**Comment by oleg-alexandrov** [comment]
Also there is bin_path() which also either goes to bin/ or to Tools/ depending on where it finds the program.

**Comment by ScottMcMichael** [comment]
I added a Theia patch which eliminates the need for this behavior.
