### ISSUE TITLE
Question about the alignment-method

### ISSUE THREAD

**Issue by sdrdis** [NeoGeographyToolkit/StereoPipeline#148]
Hi,

I have one question about the alignment-method parameter of stereo. When I read the section B.1 of the documentation, it is written:
> When alignment-method is set to affineepipolar, stereo will attempt to pre-align [...] such that pairs of conjugate epipolar lines become collinear and parallel to one of the image axes.

I plan to use a home made stereo vision algorithm, but would like to benefit from the preprocessing step of stereo. However, I need to make sure that the epipolar lines are horizontal and not vertical. Therefore, is there a way to know, after the preprocessing step, which axis (vertical or horizontal) the epipolar lines are parallel to? Or is there a way to force these lines to be horizontal?

Thanks,

**Comment by oleg-alexandrov** [comment]
I honestly don't remember now which direction the epipolar lines end up pointing. What you can do, is run disparitydebug on the obtained D.tif that comes from stereo. If affineepipolar alignment was successful, the obtained disparity in D.tif will be mostly horizontal or mostly vertical. And it will answer your question. If you want to force the lines to be horizontal (if they are not), I suggest you look at our source code in the location where epipolar alignment happens, in AffineEpipolar.cc.
