### ISSUE TITLE
Disparity is not being read correctly

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#154]
The D.tif is being saved as int32 (except for SGM), but read as float. Same for D_sub if I recall right. There should be a code for checking the type being read as in stereo_rfne.cc.  Also need to double check just in case that sparse_disp outputs int32 D_sub just as regular low-rez correlation. 

I tried fixing this once, and odd blobs are coming up. A more careful study is needed. This better be done before the release.

**Comment by ScottMcMichael** [comment]
This problem appears to have been fixed, it is at least handled in stereo_rfne, stereo_blend, and disparity_debug.  Will keep an eye out for this potential problem going forwards.
