### ISSUE TITLE
undistort_image

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#155]
This one is very slow and loads the memory fully in memory. Admittedly is a debug tool, but it better be made to work as all other tools we ship, so on large images, with multiple threads, progress bar, etc.

**Comment by ScottMcMichael** [comment]
Currently it is only designed to work on typical pinhole images which can easily be loaded into memory.  The slow speed is the result of applying our lens distortion model to every pixel.  Each model works quickly in one direction and slowly in the other and if you are going the slow direction it can be painful.

**Comment by oleg-alexandrov** [comment]
Discussed at https://github.com/NeoGeographyToolkit/StereoPipeline/issues/269
