### ISSUE TITLE
Second column in list input to dem_mosaic

### ISSUE THREAD

**Issue by SmithB** [NeoGeographyToolkit/StereoPipeline#159]
Worldview DEMs can often have a static vertical bias that needs to be corrected before the DEMs are put into a mosaic.  It's possible to do this by hand before the DEMs are input to dem_mosaic, but a clean and easy (for the users) solution would be to read a vertical offset for each DEM from the input list for DEM_mosaic, like this:
dem_mosaic -l MyList.txt -o MyDem.tif -c 2

contents of MyList.txt
DEM_file1.tif 23.1
DEM_file2.tif -16.0
DEM_file3.tif 9.0
etc

**Comment by oleg-alexandrov** [comment]
This looks like a feature which should be helpful without staying in the way for people who don't need it. I'd also welcome more thoughts on this before I get down to the implementation.

**Comment by thareUSGS** [comment]
This would be a nice feature straight from the table.

We have used a different method to get the same effect although it requires an extra file. So an alternative to adding the second field would be for dem_mosaic to recognize (and apply) the scale and offset as added (or provided) in the Tiff or copied virtual VRT header.

1.) Here is how this might work. First case requires updating the Tiff.
`gdal_edit.py -scale 1.0 -offset 15.0  rectJ21_plus15.vrt`
assuming dem_mosaic applies the scale and offset, we are done. And the Tiff maintains a nice "record" of the value for the next user.

2.) say you can't (or don't want to) edit the Tiff, then create a temporary GDAL VRT
```
gdal_translate -of VRT rectJ21.tif rectJ21_plus15.vrt
gdal_edit.py -scale 1.0 -offset 15.0  rectJ21_plus15.vrt
```
Now send dem_mosaic the rectJ21_plus15.vrt file. This again assumes dem_mosaic will apply the scale and offset defined in the label.

3.) This is a working method, but it requires an intermediate image. Do the same in (2) and then have GDAL apply the offset and scale to a temporary file prior to dem_mosaic.
```
gdal_translate -of VRT rectJ21.tif rectJ21_plus15.vrt
gdal_edit.py -scale 1.0 -offset 15.0  rectJ21_plus15.vrt

gdal_translate -unscale -ot INT16 -a_nodata 0 rectJ21_plus15.vrt rectJ21_plus15applied.tif
```
now use rectJ21_plus15applied.tif in dem_mosaic

**Comment by oleg-alexandrov** [comment]
In practice such a use case is likely rare and hasn't come up since. Normally DEMs are already aligned if bundle adjustment was used, or they should be aligned to a third-party DEM before mosaicking.

One can also use ASP's image_calc tool to apply a shift, if needed, before mosaicking.
