### ISSUE TITLE
stereo - won't get through preprocessing

### ISSUE THREAD

**Issue by egodin** [NeoGeographyToolkit/StereoPipeline#162]
I am using _stereo_ to process raw images. I used as a training/guide the asp_book-2.5.3, section 4.1 for instance. I downloaded the free digital-globe stereo-pair (Guangzhou, CH) suggested in the example, and invoked the following:

```
> stereo -t dg --subpixel-mode 1 --alignment-method affineepipolar \
13DEC28032941-P1BS-053950035030_01_P001.TIF \
13DEC28033039-P1BS-053950035030_01_P001.TIF \
13DEC28032941-P1BS-053950035030_01_P001.XML \
13DEC28033039-P1BS-053950035030_01_P001.XML dg/dg
```
It just stop early in the process, with a simple error : Stereo step 0: Preprocessing failed
Results are identical for 2.5.3 release, 2.5.2 and 2.4.2

Error is identical with my own digital globe documents that I want to ultimately analyse.

Here is the logfiles:
[vw_log.txt](https://github.com/NeoGeographyToolkit/StereoPipeline/files/799663/vw_log.txt)
[dg-log-stereo_parse-18182.txt](https://github.com/NeoGeographyToolkit/StereoPipeline/files/799662/dg-log-stereo_parse-18182.txt)
[dg-log-stereo_pprc-18211.txt](https://github.com/NeoGeographyToolkit/StereoPipeline/files/799661/dg-log-stereo_pprc-18211.txt)

and the screen output from the work so far:

![stereo](https://cloud.githubusercontent.com/assets/9801097/23308736/271ed82a-fa7a-11e6-87d2-ef36d125f87f.PNG)

I have success organizing and processing the images with _mapproject_ with a low resolution DEM, (for example at p. 30 section 5.1.6) and thus generating good output, but when invoking _stereo_ next, the same problem occur. So I assume that the XML, TIF, NTF files, from different datasets, are not likely in fault.

There is not a lot of output even when setting verbose level in .vwrc so I am not sure what to do next. Anyone else experiencing problems while executing _stereo_ ?

**Comment by ScottMcMichael** [comment]
What kind of machine are you running this on?  Maybe the images are too large?  I just re-ran this on 2.5.3 and I don't get this error.

**Comment by egodin** [comment]
Hah it is a virtual machine on my notebook - yet a recent one, SSD hard drive, intel i7 and 8Gb of RAM - but it is a good pointer you just provided. I will need to find a box somewhere to make some more tests then. Or I may try with smaller images

**Comment by oleg-alexandrov** [comment]
If you already have map-projected images, as you say, you can crop them
both to a small shared area using gdal_translate -projwin. (You can
determined the desired projwin in the GUI using Control-Mouse). You can run
stereo with these very small projected images as stereo left_map_crop.tif
right_map_crop.tif left.xml right.xml dg/dg input_dem.tif. If this still
fails, for small images, then something else could be wrong.

**Comment by ScottMcMichael** [comment]
WorldView images are quite large for something like that.  You can reduce the workload in this example by cropping the input images with --left-image-crop-win and --right-image-crop-win and that should allow it to run to completion.

**Comment by oleg-alexandrov** [comment]
To accomplish this, instead of invoking stereo you can invoke stereo_gui,
then select the desired small region in the GUI in the left and right
images using Control+Mouse, then run stereo from the menu. The
documentation explains this in more detail.

**Comment by egodin** [comment]
Great I was at a dead-end and now I have a few options to try - I will get to work and update here with details, will take the path of working with a smaller image-set. Your help is very appreciated. *Firing-up stereo-gui*

**Comment by egodin** [comment]
UPDATE: for those running the ASP suite from a Virtual Machine such as Virtualbox https://www.virtualbox.org/ -

the default settings for the virtual machine were very conservative and I used it as is the whole time. For example:
cache memory was set at 1024 Mb
and the CPU used was 1

and this regardless of the available CPU (logical/physical) and memory available on the host system.

Setting cache memory to 4096 Mb and enabling 4 CPU (maximum the Virtualbox license I use permit) made ASP overall much faster, enabling more possible threads and in addition ASP did not exit with an error during Preprocessing Step 0.

I think that a note in the documentation regarding the use of Virtual Machines to run ASP would be a nice addition, with a suggestion to crank-up the cache use and _n_-CPU. If the authors/maintainers of ASP wish so I could prepare a patch for the documentation to that effect.

**Comment by oleg-alexandrov** [comment]
I am glad you figured it out. So this is a user issue. When creating a VM the user should explicit specify how many CPUs/RAM to use.  I would not be sure this is ASP-specific enough to be in the doc. Probably ASP should print an explicit message when running out of memory. I will keep this in mind.
