### ISSUE TITLE
Add a tutorial about how to process HRSC imagery

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#163]
We lack info about how to process HRSC imagery with ASP. In my little experiements, SGM does better than our regular block matching. This blurb by Zack could be a starting point.

https://isis.astrogeology.usgs.gov/IsisSupport/index.php?topic=3799.0

**Comment by ScottMcMichael** [comment]
Added a basic example in 790a29eaeb0c583247ce4f7f33681c7a49d0146b
