### ISSUE TITLE
sparse_disp - IndexError: too many indices

### ISSUE THREAD

**Issue by egodin** [NeoGeographyToolkit/StereoPipeline#166]
While working with a dg pair, I was able to generate a decent DEM (point2mesh) from the pointcloud (dg-PC.tif) - see Figure 1. 
![screen_shot_0_0](https://cloud.githubusercontent.com/assets/9801097/24761665/15ac70a6-1aba-11e7-84ed-97e54ebe571e.jpg)
_FIGURE1: example of a point2mesh rendering_

When using point2dem, there was some issues with large holes in the slopes probably due to shadow. While reading the asp_book.pdf to learn about resolution paths for my problem, I stumbled upon figure 4.4 with this relevant caption:

> Figure 4.4: Example of a diffcult terrain obtained without (left) and with (right)
 sparse_disp. (In these DEMs there is very little elevation change, hence the flat appearance.)

It is mentioned at a few place how this could be a solution to improve DEM quality using certain type of terrains. I tried the following with my dg - with --corr-seed-mode 3 to enable sparse_disp. 

$ stereo -t dgmaprpc --corr-seed-mode 3 --corr-max-levels 2 left_mapped.tif right_mapped.tif 13APR17194548-P1BS-500075442100_01_P006.XML 13APR17194736-P1BS-500075464050_01_P006.XML dg8/dg8 cdem_dem_160521_105602.tif

Preprocessing goes fine, then after trying to resolve, found thousands of good matches and exit with a _IndexError: too many indices_

[ 2017-Apr-06 10:22:12 ] : PREPROCESSING FINISHED 
Warning: Changing the alignment method to 'none' as the images are map-projected.
Start: 2017-04-06 10:22:16.987995
T_file = dg8/dg8-L.tif
S_file = dg8/dg8-R.tif

output_prefix = dg8/dg8
Warning: Decreasing ysearch value to: 512
Setting coarse skip to: 256
Running initial search: 2017-04-06 10:22:17.001461
 --- ep vec estimated at(0.984946,-0.172861), tol=24.000000, ep_dist_f90=60.255378
----------refining to 128---------
Refining: 2017-04-06 10:24:23.092187
    searched 4726 points, found 4573 good matches
Traceback (most recent call last):
  File "/home/egodin/asp-2.5.3/libexec/sparse_disp", line 1409, in <module>
    main()
  File "/home/egodin/asp-2.5.3/libexec/sparse_disp", line 1235, in main
    refine_pts=test_pts[to_refine,:]
IndexError: too many indices
Stereo step 1: Low-res correlation with sparse_disp failed

I tried the same process using the manual suggested sample images 
file:///Ganzhou/13DEC28033039-P1BS-053950035030_01_P001.TIF with the same outcome.

Is there any documentation on sparce_disp about this error (Too many indices) or any other suggestions on which steps could be used to help obtaining a good DEM?

thank you,

Etienne G.

**Comment by ScottMcMichael** [comment]
Can you post the series of steps you took using the sample images from the manual so I can exactly recreate your process?

Scott

**Comment by egodin** [comment]
Scott, thank you for the follow-up :+1: 
here are the steps:

$ mapproject -t rpc --mpp 0.5 srtm_59_08.tif 13DEC28032941-P1BS-053950035030_01_P001.TIF 13DEC28032941-P1BS-053950035030_01_P001.XML left_mapped.tif

$ mapproject -t rpc --mpp 0.5 srtm_59_08.tif 13DEC28033039-P1BS-053950035030_01_P001.TIF 13DEC28033039-P1BS-053950035030_01_P001.XML right_mapped.tif

$ stereo -t dgmaprpc --corr-seed-mode 3 --corr-max-levels 2 left_mapped.tif right_mapped.tif 13DEC28032941-P1BS-053950035030_01_P001.XML 13DEC28033039-P1BS-053950035030_01_P001.XML dg2/dg2 srtm_59_08.tif

using included default stereo.default as is

In attachment, I pasted my console (I re-ran it this morning before posting to double-check my input) 

[console.txt](https://github.com/NeoGeographyToolkit/StereoPipeline/files/905508/console.txt)

**Comment by ScottMcMichael** [comment]
I went through your procedure and did not hit the same error so I am not sure what is going on for you.  Here are a few things you could try:

- The file sparse_disp.py has been updated since the release you are using.  I don't believe that line of code has changed but maybe something else has fixed the problem: https://github.com/NeoGeographyToolkit/StereoPipeline/blob/master/src/asp/Tools/sparse_disp.in

- See if other options help fill in those holes.  sparse_disp is really intended for barren regions like snow and may not improve performance on slopes.  You might get better results by increasing the kernel size or playing around with other correlation options.

- Use our new SGM algorithm.  This is not in the release yet but you can find it in the latest dev build (https://byss.arc.nasa.gov/stereopipeline/daily_build/) and hopefully a new release within the next week.  This algorithm performs much better on some images but it will require you to be more aware of RAM issues, see the new documentation for details.

**Comment by egodin** [comment]
@ScottMcMichael Interesting suggestions, I am currently testing these. I downloaded the daily build and compiled it - possibly I had incompatible modules/libraries being used (ex GDAL, numpy,scipy) installed on my machine and conflicting with those provided with ASP, causing a malfunction somewhere; also installed the latest sparse_disp.py

After recompiling I am running and went further in the processing than initially - so good news. 

My digitalglobe image is snowy, and the snowy terrain was well processed without sparse_disp.py so maybe I will try to tune up other parameters such as kernel size as suggested instead of using --corr-seed-mode 3

Meanwhile, would this be possible to see a snippet of a typical console output - just after this

--------output stats------
99th percetiles (rx,ry) = (140.90 39.00)
95th percetiles (rx,ry) = (99.00 28.00)
90th percetiles (rx,ry) = (67.25 20.50)
84th percetiles (rx,ry) = (51.00 14.25)

it keep processing for a very long time without further output, one instance more than 8 hours -

(I will close the issue soon / after your answer - as the initial problem is resolved - thanks for your help)
