### ISSUE TITLE
Manage Camera Jitter in ISIS3 Sessions

### ISSUE THREAD

**Issue by dpmayerUSGS** [NeoGeographyToolkit/StereoPipeline#171]
Jitter is present in camera other than those in the DigitalGlobe constellation.  In particular, CTX image data are affected by a type of jitter that creates similar intersection error features as jitter in WorldView-2 image data. Theoretically, the same piecewise approach that is used to correct pointing and timing errors in DG data should help mitigate jitter in simple line scan cameras like CTX. It would be great if the various jitter management config options that are available for DG data could be extended to planetary image data as well. 

Is this a feature that could be added in a future release of ASP?

**Comment by oleg-alexandrov** [comment]
David, this is a good point. Jitter is something we do plan to tackle at some point soon if a certain project gets funded. 

The current approach, for WV-2, which I put in, is, I believe, not sufficiently rigorous. It does reduce the final intersection error, but I did not spend a lot of time qualifying the effect on DEM accuracy. There are plenty publications on this, but we'd need to be funded to work on such corrections.

**Comment by oleg-alexandrov** [comment]
ASP has a jitter tool now and there is an example for CTX. It can constrain the camera positions, orientations, and ground locations (via staying close to initially triangulated points or a third party DEM). Can resample the camera positions and poses. Multiple images are supported.  It would be nice to do more thorough tests for CTX. https://stereopipeline.readthedocs.io/en/latest/tools/jitter_solve.html
