### ISSUE TITLE
hiedr2mosaic.py fetch option

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#174]
This tool should have an option to automatically fetch its inputs (maybe also filtered by a tag, e.g., RED). HiRISE images are split into many chunks and it is a bit of a pain to use the search engine to find the path to the correct dataset and pull the relevant dozen files. Maybe there is some solution already I am not aware of.

**Comment by ScottMcMichael** [comment]
Added in f1c71d0c2b4444b8c9b0fb9cd816e815008502ef
