### ISSUE TITLE
mapproject_single bug

### ISSUE THREAD

**Issue by ScottMcMichael** [NeoGeographyToolkit/StereoPipeline#175]
The camera_bbox call in mapproject_single fails with some DEM/camera combinations unless the "quick" parameter is set to true.  Test with IceBridge images to see this.

**Comment by oleg-alexandrov** [comment]
wanna specify a testcase?

**Comment by ScottMcMichael** [comment]
This issue occurs when using a very large DEM with a PinholeCamera image with lens distortion.

**Comment by oleg-alexandrov** [comment]
If you don't specify a testcase this will be lost.

**Comment by ScottMcMichael** [comment]
Hopefully fixed by VW change 2e652a02aea31a1f72d89c629ddd473993541aa7
