### ISSUE TITLE
hiedr2mosaic.py has a bad error-check mechanism

### ISSUE THREAD

**Issue by rbeyer** [NeoGeographyToolkit/StereoPipeline#176]
After initialization, hiedr2mosaic.py counts up the number of CCDs it got.  If the match cube value is numerically higher than the count of CCDs, it issues a warning and sets the match cube to the number of CCDs minus 1.

This was a safety check meant to help people from entering erroneously high match cube values, but it actually breaks if CCDs 4,5,6,&7 are 'on' and the match cube is set to 5 or higher (which it should be able to, since CCD 5 is one of the CCDs in the observation).

Not sure why we thought that using a simple 'count' of CCDs was a good check to use, or why arbitrarily changing the match cube was wise.  We were probably just too lazy to write the logic that would extract the CCD 'number' from each of the filenames and do a proper check.

The better behavior would be to find the CCD number of each of the CCDs submitted, and if the match cube is equal to the CCD number of any of those, then it is fine.  If not, it should probably just error out and not proceed.

**Comment by ScottMcMichael** [comment]
Rewrote to check that both selected CCD files are present: 179416bad32b65209a31aed70165e08d2ddd3045
