### ISSUE TITLE
stereo subpixel refinement

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#178]
Our subpixel methods seem to be not so good. We have Ara's approach, which is kind of slow, and our newer approach, which only works with MGM/SGM. Ideally each of our subpixel approaches should work with each of our integer correlation approaches. Also, it would be nice to study the literature, and also MicMac (which apparently is better), and see what is the state of the art or what is already implemented.

Hopefully we'll get to this if we get funding approved for core ASP work.

**Comment by oleg-alexandrov** [comment]
Papers: https://www.researchgate.net/publication/5654753_Efficient_subpixel_image_registration_algorithms
http://www.tectonics.caltech.edu/slip_history/spot_coseis/pdf_files/Leprince2007TGRS.pdf

**Comment by ScottMcMichael** [comment]
Added a phase correlation subpixel algorithm based on the first paper in 3808dad5d5786e7093e3cd17eb22eeb43f3a98f2.  So far it does not look like it performs better than our existing methods.

**Comment by oleg-alexandrov** [comment]
That is great. Hopefully there is some documentation or release notes.

**Comment by oleg-alexandrov** [comment]
In my experience stereo with mapprojected images and --stereo-algorithm asp_mgm --subpixel-mode 9 gives the best results.
