### ISSUE TITLE
Allow bundle_adjust to modify spice kernels

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#179]
When bundle_adjust is used, it writes its adjustments as .adjust files, except for pinhole cameras where the adjustments are incorporated directly into the cameras. It would be nice if this functionality also works for .cub files, so we'd  modify them directly, which means modifying the spice info of .cubs. In this way, the .cub files can be used later on with other ISIS tools and so far two users asked for it. 

Note that bundle adjust is now able to take pc_align's transform and write .adjust files. If the functionality proposed above is implemented, we will then automatically be able to go from a pc_align transform back to a .cub file applying that transform.

**Comment by dshean** [comment]
Might also be useful to update the DG xml files - ideally both the RPC coefficients (which I believe is already supported through other recently added tools?) and the linear camera model.  But I'm not sure that the current user demand for this functionality justifies the effort required to implement.  Just wanted to add a note to consider a more general approach.

**Comment by oleg-alexandrov** [comment]
ISIS is moving more towards using CSM. For that, ASP can save camera files that incorporate any adjustments to them and can be used with external tools such as SOCET SET. https://stereopipeline.readthedocs.io/en/latest/examples/csm.html#exporting-csm-model-state
