### ISSUE TITLE
Create DEM from many (>20) drone images

### ISSUE THREAD

**Issue by jpwhitney** [NeoGeographyToolkit/StereoPipeline#181]
Not sure if this is the right place to ask, but I'm trying to create a DEM from drone photos which have GPS coordinates, can this be done with this tool?

Also are there examples to follow for this use case?

**Comment by ScottMcMichael** [comment]
Questions like this should go in our support forum:  https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/ames-stereo-pipeline-support

The issues list is for bug reports and specific feature requests.
