### ISSUE TITLE
mapproject for HiRISE with MOLA flat datum significantly slower than cam2map

### ISSUE THREAD

**Issue by AndrewAnnex** [NeoGeographyToolkit/StereoPipeline#186]
I was interested to see if the multi-threaded mapproject command provided by ASP would be faster than using cam2map4stereo and found it to be significantly slower despite using all available threads (roughly 2-3X slower on a 16 thread cpu, about 6-7m per 1024*1024 tile). I used the 2.6.0-2018-07-06 build for the test. I used  `mapproject -t isis MOLA hiedr2mosaic'd.cub out.tif` for the test, another test I provided a t_srs parameter with the same level of performance.

**Comment by ScottMcMichael** [comment]
Which HiRISE data did you run the test on?

**Comment by AndrewAnnex** [comment]
I used a .cub file produced using hiedr2moasic in place of using cam2map4stereo. If you want to know the specific HiRISE image I could also post that, it was in a equatorial region in any case.

**Comment by ScottMcMichael** [comment]
Yes, I would like to use the specific image to make sure I see the same behavior.

**Comment by AndrewAnnex** [comment]
ESP_019835_1880
https://www.uahirise.org/ESP_019835_1880

**Comment by AndrewAnnex** [comment]
shouldn't mapproject have the smarts to handle the threads? It seems that single threaded cam2map should not be faster since it is also using the same isis3 camera library codes.

**Comment by oleg-alexandrov** [comment]
It is suggested to use CSM cameras for HiRISE, CTX, etc. Then mapprojection is about 10x faster (for each projection into the camera) and also multi-threaded. https://stereopipeline.readthedocs.io/en/latest/examples/csm.html
