### ISSUE TITLE
Automated gcp picking

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#188]
Currently ASP allows the following flow. Given two images to be used for stereo, a third map-projected image which may be different than the two, and a DEM, manually tie features from the two first images with points from the third in stereo_gui. Then, via the DEM, we obtain the xyz coordinates of these features, hence they can be used as GCP in bundle adjustment. 

The manual process is needed since the third image may be very different than the first two, maybe acquired  years later, with a different satellite, under different illumination conditions, in a different season (e.g., ice vs no ice). Then, automated interest point matching fails. 

It would still be nice if we offer the option to automate this step, and allow the user to inspect and edit the results, so the manual approach would be used when the automated one fails.

**Comment by ScottMcMichael** [comment]
Added more options in 0791d444392deb47641e4d31d6887bd772e38c2a including the ability to manually move around IP.  I expect we will get some suggestions when someone seriously tests it out.

**Comment by oleg-alexandrov** [comment]
Reopening this. It would be nice to get a non-gui tool which automates and connects all this logic, for finding interest points, including between raw images and also between raw and the georeferenced image, and then it would save the gcp, all without the user having to open up the gui just to click on "save gcp".
