### ISSUE TITLE
stereo_gui, interest points, and zoom all images to same region

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#192]
Zooming all images to same region and ip match display are independent functions, and it appears that they don't work well together.  There was a fix recently, but I think it did not go far enough. Here is the problem. Several (say 3 or 4) georeferenced images are open, and ip are picked by hand. Then ip are saved to file. Then they are loaded back, plotted, and one sets zooming all images to same region. Their position is now wrong. And I think it stays wrong after this zoom is turned off. Likely the conversion to the right projection is not done.

**Comment by ScottMcMichael** [comment]
Fixed in da14faa0b38d958b2c590df7098f9d087bc7e40b
