### ISSUE TITLE
sparse_disp and the search range

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#193]
When the search range is being determined, in read_search_range_from_dsub(), in stereo_corr.cc, we do not take into account that D_sub produced by sparse_disp does not have to have the same size as L_sub, which is the case when we don't use sparse_disp. Likely this is a bug. 

Yet, later in SeededCorrelatorView() when we use D_sub to find the disparity D, things are scaled correctly. So perhaps the effect of the above is minor or reduced only to printing incorrect values on screen. 

This will need to be carefully traced through the various approaches of creating the disparity and fixed if a bug is found.

**Comment by ScottMcMichael** [comment]
Fixed in 880f12f63e53d6fca9da48abeec84c88bb254c2d.

When comparing before/after results this did not change things much, probably because the scaling was done correctly in SeededCorrelatorView.
