### ISSUE TITLE
dem_mosaic --save-index-map nodata

### ISSUE THREAD

**Issue by dshean** [NeoGeographyToolkit/StereoPipeline#196]
The default nodata value for the output integer index map tif is set to 0.  The DEMs list uses a 0-based index.  So the first DEM in the list is indistinguishable from nodata during subsequent analysis.

Either need to change default nodata value, or increment DEM indices (both when writing pixels and writing the txt list).  I think the latter would be a better solution.

**Comment by oleg-alexandrov** [comment]
David, I took a look. I verified that the default output nodata value for the index map tif is actually what the user sets it to be, and by default, is copied from the first DEM. Can you check what that value is for that first DEM, or what you are setting --output-nodata-value to? I have a testcase, where in first-index-map.tif I see NoData Value=-3.4028234663852886e+38 and I just used the defaults. If there is still a problem, I'll look again.

**Comment by dshean** [comment]
Ah, yes.  I'm feeding time-sorted DEMs to dem_mosaic and generating first and last mosaics.  Some of the early DEMs were generated with workflow that used ndv of 0, while later DEMs use -9999.  I was not specifying output ndv, so dem_mosaic was using that 0 value for some outputs.  

Seems like for integer index maps, we should force output ndv to be 0, and start the DEM indices at 1, regardless of what the user specifies.  Seems unnecessary to have float32 values for this output data type, just to accommodate a user-defined ndv.  But, I realize this is not widely used functionality, so I can live with manually set output ndv to something that won't conflict with DEM indices.
