### ISSUE TITLE
ip match fixes

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#197]
It looks like  --nodata-radius is not having an effect. 

It would be nice to filter IPs from the top/bottom, as well as the sides. It could be useful if there are distortions at the edges of the images which are unaccounted for, and which complicate the bundle_adjustment.

**Comment by ScottMcMichael** [comment]
--nodata-radius will filter out along the edges which will work for removing edge_ip as long as nodata in the image interior does not make that problematic.  Closing this unless it becomes a problem.
