### ISSUE TITLE
Enhancement to the hillshade tool

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#199]
If one hillshades a DEM, then reprojects it, so that the image (as viewed without georeferencing) rotates say by 90 degrees, the hillshaded DEM changes drastically even though it is the same surface on the planet.  The reason for this is because our azimuth and elevation angle and normal computation are all  in respect to image orientation and does not use the georeference information. 

This breaks pc_align with the hillshading mode when the two DEMs to align have different projections. 

A solution here would be a flag called --use-georef, when the behavior of hillshade would change to:

(a)  The azimuth and elevation angles would be measured at the center of the DEM, in respect to the local East axis. 
(b) The computation of normals would take into account the georeference, rather than just the heights. So, one would find xyz = cartesian coordinates at pixel ij, xyz1 = cartesian coordinates at pixel i+1, j, xyz2 = cartesian coordinates at pixel i, j+1, and then compute the normal by taking the cross product of xyz1-xyz and xyz2-xyz (need to check if the order is correct here so that the normal points up). This then would be dotted with the sun direction from the previous step, to compute the hillshaded value. 

This would result in the DEM being hillshaded correctly regardless of projection. This --use-georef flag would then be passed to pc_align with the hillshading option.

**Comment by ScottMcMichael** [comment]
I added an improved method in 85cd5d1711daeea35385cc80b1959531e8673982.  This should be good enough unless someone attempts a very tricky alignment case.
