### ISSUE TITLE
Adding another algorithm to pc_align

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#200]
It would be nice to evaluate this open source algorithm:

https://github.com/IntelVCL/FastGlobalRegistration

The people behind it are at Intel Labs. It claims to be faster than ICP and deal well with partial overlap (which confuses ICP, that's why we have our sometimes unreliable --max-displacement option). 

It likely will take less than a day to simply evaluate it on our existing pc_align test suite, without hooking it up, so with its provided command line tool, and checking if it does well if the source cloud extends way beyond the reference cloud, where again ICP fails without throwing away points at a certain distance in advance.

**Comment by dpmayerUSGS** [comment]
Would this feature include the extension of the algorithm to handle >2 partially-overlapping point clouds that is mentioned in the original paper (https://github.com/IntelVCL/FastGlobalRegistration/blob/master/docs/fast-global-registration.pdf)?

**Comment by oleg-alexandrov** [comment]
I added the two-cloud option for this algorithm and tested it quite a bit. It can be invoked with --alignment-method fgr. It can perform better than ICP when the clouds are close enough to each other but there is a large number of outliers, when it can function with very large --max-displacement, as it does some kind of cross-check. It does worse than ICP if the clouds need a big shift to align. This should be in the daily build in a day or two.
