### ISSUE TITLE
image2qtree is broken

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#201]
As I recall, image2qtree was able to create a nice kml tree (with png tiles) from any hillshaded geotiff DEM (such as created with our hillshade tool) with no extra work. Now it appears I need to invoke it as 

image2qtree DEM_HILLSHADE.tif --pixel-scale .0039215686274509 

which makes me think it does not read correctly uint8 images with the maximum value of 255. If I invoke it without that pixel scale option, I think it multiplies the image pixels by 255 again, or something, since the output is almost totally white. Maybe some changes we did recently prevents it from inferring the right format/scale for the input files?

**Comment by ScottMcMichael** [comment]
Fixed in VW commit 05751556c092d6902f413f9db59f32cc264aa272.
