### ISSUE TITLE
Float optical center for each image individually during bundle adjustment

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#202]
Often times when historical images are scanned, the scale (focal length) is quite consistent, but there can be an offset among the various images due to inconsistency during scanning, hence the optical center can vary. It would be nice if bundle_adjust would not enforce that the optical center is the same for all images, as an option. This would require quite a lot of refactoring work given the current implementation. Maybe if we get funding to work with such imagery.

**Comment by ScottMcMichael** [comment]
Added in 30f37bff6748e1673cbd44290399c55a70b688c9.
