### ISSUE TITLE
Trouble with mapproject

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#204]
Sometimes maproject cannot project onto the datum, but it can over a DEM. Here's a sample command:

mapproject WGS84 1220996672.27391028_sc00110_c1_PAN.tiff tmp.tif  

In this case the RPC model is embedded inside of image. More details are available offline.

**Comment by ScottMcMichael** [comment]
Fixed in ca90dafd15a57b9bb3db84d059607be0d6429582
