### ISSUE TITLE
RPB files in ASP

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#205]
When we invoke stereo as

stereo left.tif right.tif left.RPB right.RPB  run/run

(and maybe even bundle_adjust) it refuses to run even so .RPB files is a format we can read via GDAL. 

When one invokes cam2rpc as:

cam2rpc input.tif input.RPB output.xml 

it complains, but goes forward. 

Both of these should be fixed, and tested with stereo, bundle_adjust, mapproject, and cam2rpc. 

In short, we should make .RPB an accepted camera model just like .xml, and associate it with the RPC camera session. Should be little work. The same test case as for the previous issue can be used.

**Comment by ScottMcMichael** [comment]
Fixed in 4384eeef82fb9f666f20dbed38a3e4c1f09611b9.
