### ISSUE TITLE
Support return filtering of las files.

### ISSUE THREAD

**Issue by ScottMcMichael** [NeoGeographyToolkit/StereoPipeline#208]
Liblas has some support for filtering returns in las files which may be useful in some situations.  We should get an example data set and experiment with this.

**Comment by oleg-alexandrov** [comment]
Liblas is no longer developed. We still use it though for point2las but hope to transition to PDAL one day.

PDAL has an entire filtering pipeline. https://pdal.io/stages/filters.html

It is probably best ASP clouds are converted to LAS with point2las, then filtered in PDAL. That toolset can create DEMs too, btw, or the las file can be brought back to ASP for further processing.
