### ISSUE TITLE
Bus error / Segfault on Stereo_Fltr

### ISSUE THREAD

**Issue by zmoratto** [NeoGeographyToolkit/StereoPipeline#21]
Reported by Shean:

Stereo Session: DG
System: OSX 10.6 64 bit
Build: Local Custom

This happens specifically on the Good Pixel Map generation step:

NASA Ames Stereo Pipeline 2.0.0_pre
  Build ID: b99882a

Built against:
  NASA Vision Workbench 2.2.0_post
    Build ID: 99860e5
  Boost C++ Libraries 104800
  GDAL 1.9.0 | 20111229
  Proj.4 470

stereo_fltr -t dg --threads=7 -s dem/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500/stereo.default dem/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500/WV02_11FEB241515255-P1BS-1030010009C65700.tif dem/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500/WV02_11FEB241514058-P1BS-1030010009B0B500.tif dem/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500/WV02_11FEB241515255-P1BS-1030010009C65700.xml dem/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500/WV02_11FEB241514058-P1BS-1030010009B0B500.xml dem/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500/WV02_11FEB241515255-P1BS-1030010009C65700__WV02_11FEB241514058-P1BS-1030010009B0B500
    --> Setting number of processing threads to: 7

[ 2012-Apr-26 01:14:44 ] : Stage 3 --> FILTERING 
    --> Cleaning up disparity map prior to filtering processes (1 pass).

```
    --> Good Pxl Map: [...............................................] 0%Bus error
```

22.476u 4.313s 0:22.49 119.0%   0+0k 0+3io 1051pf+0w
Failed

**Comment by oleg-alexandrov** [comment]
(And the issue was closed, unlike what I thought when reading it.)

**Comment by dshean** [comment]
Wow, hard to believe that was 10 years ago!  Nice to be reminded about those early days working with @zmoratto, and the excitement of first ASP for Earth test results :)

**Comment by dshean** [comment]
One thing I don't miss is dealing with compiler errors.  Many, many thanks to all of the ASP devs over the years, includign @oleg-alexandrov for preparing and maintaining an efficient build system, distributing precompiled binaries, and migrating to conda.
