### ISSUE TITLE
Make filtering by triangulation error more robust in bundle_adjust

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#211]
There is that testcase from David where triangulation error is several km for some image pairs for WV. I wonder if there is any quick fix for this (maybe we overlooked something), or one should put up with that until outlier filtering happens at the end (when it is turned on).

**Comment by ScottMcMichael** [comment]
Added the option --ip-triangulation-max-error in f9af8d4311d15eccfd958a109cd66f6a2364ceec which removes high error IP matches before the first optimization pass.

**Comment by oleg-alexandrov** [comment]
That may be good enough for now, perhaps. Maybe at some point this could be automated based on some statistics if desired. Hoping this is documented and in the release notes.
