### ISSUE TITLE
Build fails due to bzip2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by latenooker** [NeoGeographyToolkit/StereoPipeline#212]
build.py is giving me the following error on Ubuntu 14.04:

========== Building: bzip2 ==========
========== bzip2.fetch ==========
Downloading bzip2-1.0.6.tar.gz: 17 kB
Done
Failed to build bzip2 in attempt 0 Package[bzip2] Checksum on file[/home/look/projects/BinaryBuilder/tarballs/bzip2-1.0.6.tar.gz] failed. Expected 3f89f861209ce81a6bab1fd1998c0ef311712002 but got bb38b5f76bded2ef173d902ff0267de628ed4bbd. Removed!

I have bzip2-1.0.6 installed on my system.

**Comment by ScottMcMichael** [comment]
Before we try to debug this, are you sure you want to compile ASP yourself instead of using one of our binary releases?

Scott

**Comment by latenooker** [comment]
Thanks for your reply, Scott. I will stick to the binary release.
