### ISSUE TITLE
pc_align issue applying translation?

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#213]
Hi Scott,

I just noticed some weird behavior using pc_align/bundle_adjust when applying transformations to pinhole cameras... I'm not sure if you or Oleg changed something recently?

Basically, in the previous release (before 5th Dec build), when I computed the inverse transform between my ASP DEM and a reference DEM, I got this:
cat trans1-inverse-transform.txt
   0.9999670806654368 -0.007804132501920781 -0.002221058583527107    -44439.16512991776
 0.007781477405351556    0.9999193979741426  -0.01003225619249146     15910.73616510996
 0.002299172618327889    0.0100146428200877    0.9999472089737308     61848.27153707921
                    0                     0                     0                     1

And when I applied it to my cameras (using bundle_adjust with --max-iterations 0 and --initial-transform trans1-inverse-transform.txt), I got adjust files like this:
cat ba3-guatemala_53.adjust.orig
-38.7933010918040964 28.7340960958972573 -53.1627361173741519
0.999949095451905356 0.00834329141440272315 0.00473620600724225342 0.00312479534491459654
(these are good, and all is well in this case).

... HOWEVER, using the 5th Dec 2018 build, and with the exact same input files and commands, I get the following:
cat trans1-inverse-transform.txt
   0.9999670806654368 -0.007804132501920781 -0.002221058583527107    -44439.16512991776
 0.007781477405351556    0.9999193979741426  -0.01003225619249146     15910.73616510996
 0.002299172618327889    0.0100146428200877    0.9999472089737308     61848.27153707921
                    0                     0                     0                     1

...this is the same as before, BUT(!) the adjust files are totally different:
cat ba3-guatemala_53.adjust
-44567.2228254281654 15888.8807767241487 61821.1216514268162
0.999949095451905356 0.00834329141440272315 0.00473620600724225342 0.00312479534491459654

It looks like bundle_adjust is doing something strange when applying the translation. The rotation part looks ok though.

Any thoughts?... maybe it's related to the changes you've been doing with bundle_adjust? It looks like pc_align is behaving normally.

Cheers,

James

**Comment by adehecq** [comment]
Hi James,

Oleg noticed something wrong with bundle_adjust in the latest build, and added a fix that should be available. Hopefully that will fix the issue,
Cheers,

Amaury


On Dec 6, 2018, at 01:54, jchollingsworth <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like bundle_adjust is doing something strange when applying the translation. The rotation part looks ok though.

**Comment by oleg-alexandrov** [comment]
Sorry for not responding earlier. I will look at this early next week.

**Comment by oleg-alexandrov** [comment]
Scott fixed this and the latest build should have the fix.
