### ISSUE TITLE
bundle adjustment and residuals

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#214]
It appears that when invoked with --initial-transform, bundle_adjust does not compute the residuals correctly, for example, the pointmap.log is wrong. Maybe they are computed before the transform is applied or something else is fishy, as the residuals appear large. If however the cameras with the transform applied are saved, without any iterations, and bundle adjust is ran again with the transformed cameras, also with zero iterations, this time the residuals are fine. I will look at it at some point soon.  Can be related to https://github.com/NeoGeographyToolkit/StereoPipeline/issues/213, I think the recent massive refactoring of bundle_adjust missed some things.

**Comment by ScottMcMichael** [comment]
Is there a test case I can look at?

**Comment by ScottMcMichael** [comment]
This is the same problem as in #213.
