### ISSUE TITLE
Add method to convert from opticalbar model to RPC pinhole model.

### ISSUE THREAD

**Issue by ScottMcMichael** [NeoGeographyToolkit/StereoPipeline#216]
It would be nice if convert_pinhole_model can go from the optical bar model to a pinhole model with RPC coefficients, because sooner or later we can experiment with correcting distortions that the optical bar model cannot handle. 

Just as an idea, it should be possible to find GCP for each individual image. Doing interest point matching from the SRTM to an ASP DEM with MGM it is possible to go from a true point on the ground in the SRTM to the ASP DEM, and from there by projection to each of the two cameras. With enough such GCP we could do as in one of those papers, fit an  RPC model to each camera separately. I don't think we need to do that. This is just a thought of the power of interest point matching. It can find tie points between two DEMs out of which one is quite warped or even squished or translated.

**Comment by oleg-alexandrov** [comment]
I put in all the code in VisionWorkbench, but it is turned off until we move the optical bar model there from Stereo Pipeline. It will also need testing.

**Comment by oleg-alexandrov** [comment]
I tested this and it works well.

**Comment by oleg-alexandrov** [comment]
I am keeping this open for a little longer until the optical bar model is moved to VW from ASP just to make sure we don't forget about it. It may take a while.
