### ISSUE TITLE
stereo_gui crashes on the mac when adding interest points

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#217]
When one the mac, with two images open side by side, if one right-clicks to add interest points, stereo_gui crashes. This does not happen on Linux, so it is strange. Was reported by user. Need to verify on our Mac when shutdown is over.

**Comment by ScottMcMichael** [comment]
Fixed by f9427987a113bb01a779d8d636e979b228d24f94
