### ISSUE TITLE
Add more rotation options to image_mosaic

### ISSUE THREAD

**Issue by ScottMcMichael** [NeoGeographyToolkit/StereoPipeline#223]
In addition to the 180 degree rotation options, some images need to be rotated by +/- 90 degrees.

**Comment by ScottMcMichael** [comment]
Added in 879422634f85f29283359c8ffa08eaacffc7e3f6.

**Comment by jchollingsworth** [comment]
Picking up on an old issue... 

...it would be **incredibly** useful if image_mosaic could have an option to output the final mosaic in some arbitrary angle (not just 90 or 180). I guess cubic resampling could be the default (maybe with other resampling options from gdal?). 

Cheers, J
