### ISSUE TITLE
Improve parsing of inputs arguments

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#225]
Calling stereo with the same dem used for mapprojection as for computing the low-res disparity with the option --disparity-estimation-dem  dem.tif --disparity-estimation-dem-error  val causes the error:

"The following input argument shows up more than once and hence cannot be parsed correctly: dem.tif

There was a good reason for as to why an input cannot show up more than once, I think it makes handling multi view stereo more complicated. In any case, or parsing must be tweaked to address the above issue as what is repeated is a DEM and not an image or a camera.

**Comment by oleg-alexandrov** [comment]
Apparently --corr-seed-mode has another problem, even after using different names for the two DEMs. The error is:

"num_stereo_pairs,1

Creating output directory: "19_206__19_207"
Using session: pinholemappinhole.

None"

I don't think we ever tested --corr-seed-mode 2 with mapprojected images.

**Comment by ScottMcMichael** [comment]
It looks like there is already an explicit check to prevent this combination of options but depending on the input command something else may fail first.  I added a note in the manual that DEM disparity estimation is not compatible with map projected images.
