### ISSUE TITLE
lon-lat-limit in bundle_adjust

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#227]
Hi guys,

A quick question re lon-lat-limit option in bundle_adjust...

... I have some pre-existing match files (from earlier run of ipfind +ipmatch), which cover quite a big region. I would like to bundle_adjust some images with these matches, but over a more limited region. I therefore tried using --lon-lat-limit, like so:
--lon-lat-limit 48.83 36.4325 49.92889 37.11

Bundle_adjust runs fine, but I notice the initial_points.kml and final_points.kml show all the matches... they haven't been cropped by the lon/lat condition.

Is this behavior correct? if so, does this option only work if bundle_adjust does the IP matching?

Cheers,

J

**Comment by ScottMcMichael** [comment]
That is the expected behavior as that filter is only applied when computing the .match files, not when reading them in from disk.  Is it possible to recreate the match points in bundle_adjust?

**Comment by jchollingsworth** [comment]
Ok, that clarifies things. Indeed, I tried letting bundle_adjust find the matches, and lon-lat-limit worked perfectly. It could be useful to have this condition apply when using pre-existing matches, but probably a low-priority request... Thanks :)

**Comment by ScottMcMichael** [comment]
Unfortunately it would take some refactoring to allow that and avoid code duplication but if it becomes a problem we can take a look at it in the future.
