### ISSUE TITLE
pinhole model header lines

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#228]
Hi guys,

Just noticed a problem using tsai files generated with cam_gen followed by orbitviz:
VW Error: PinholeModel::read_file(): Could not read the x focal length

The problem seems to be due to the cam_gen tsai starting lines:
VERSION_4
PINHOLE
fu = ...blah blah
... where-as orbitviz expects:
VERSION_3
fu = ...blah blah

I also found mapproject could not parse the VERSION_4 format:
VW Error: PinholeModel::read_file(): Could not read the x focal length

In addition... it would be nice if there was an option in cam_gen to output ~zero starting values for distortion (rather than NULL), so they can be floated later. Otherwise we need to copy and paste them in manually.

Cheers,

J

**Comment by ScottMcMichael** [comment]
Which daily build are you using?  Could you send me an example .tsai file that is not being read and the commands you are using to read it?

Scott

**Comment by jchollingsworth** [comment]
Hmmm... I'm using 6th Feb 2019... but now I can't reproduce this error! I might have messed up somewhere. Apologies...

**Comment by ScottMcMichael** [comment]
Bugs that fix themselves are the best kind!
