### ISSUE TITLE
Optical bar and --initial-transform in bundle_adjust

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#235]
I think --initial-transform (obtained from pc_align) does not work as it should with the optical bar model in bundle_adjust. I am not fully sure. I had an example where I applied it with zero iterations, and the new cameras created a DEM in the wrong place. There is a chance I made a mistake. I don't think we ever tested though this procedure with the optical bar model.

**Comment by ScottMcMichael** [comment]
Fixed in 924633282107aa38f858355880b0158871c643b2
