### ISSUE TITLE
Floating more parameters in the optical bar model in bundle_adjust

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#236]
Currently, bundle_adjust with the optical bar model floats only the film scan rate and aircraft speed. I think it should also float the scan angle, even if nominally it is fixed and known, or at least offer it as an option (cropping the picture affects the scan angle). And we should float the forward tilt, as that one likely changes quite a bit. I must say my knowledge of the optical bar model is still somewhat rudimentary, and maybe I miss something.

**Comment by ScottMcMichael** [comment]
I switched to a slightly different version of the model which floats the speed and a factor multiplied by the motion correction value.  This should be a bit more capable than adjusting the scan rate.
