### ISSUE TITLE
Sampling rate for images when changing the camera model

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#238]
Our stereo and bundle_adjust tool when invoked with Photometrix and other pinhole models compute an approximate model on the fly which is faster to evaluate either for distortion or distortion computation. The problem is that this approximate model computation can be very slow for huge images as we use a hidden default sampling rate of 50 pixels. I think stereo, bundle_adjust, and convert_pinhole_model should take an input a --num-samples-per-image flag with a sensible default. The same number should be passed to the function that computes undistortion for RPC distortion as the same logic is used there.

**Comment by ScottMcMichael** [comment]
The sampling rate should now be auto-computed to a reasonable value in VW.
