### ISSUE TITLE
sfm improvements

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#244]
Hi guys,

I've been looking at COLMAP lately, and it's a pretty great open source sfm pipeline. Better than Theia (which I've never had much success with). Looks like it should be relatively straightforward to integrate with ASP. It would be pretty neat to get this aspect of ASP working perfectly.

https://colmap.github.io/

One for a rainy day ;)

J

**Comment by oleg-alexandrov** [comment]
This is good to know. I appreciate you sending us a script for conversion from this tool to ASP's format.

**Comment by oleg-alexandrov** [comment]
In the meantime the Theia SfM solution improved, and was used for pretty large datasets (hundreds of images). There are also tools in ASP for merging and splitting SfM reconstructions. https://stereopipeline.readthedocs.io/en/latest/examples/sfm_iss.html#sfm-iss
