### ISSUE TITLE
common lon,lat,height values for 3 corner coordinates in cam2rpc generated xml file, does it affect the obtained rpc solution ?

### ISSUE THREAD

**Issue by ShashankBice** [NeoGeographyToolkit/StereoPipeline#250]
The output file from cam2rpc with dem-file option has common latitude, longitude and height above ellipsoid values for 3 out of 4 corner coordinates in the output xml file. I wonder how much that would be affecting the solution of the obtained rpc model. I should add that the mapprojected data using the obtained rpc files plots at about the expected place.
This is same when I invoke the cam2rpc tool with either rpc or pinhole session on planetscope cameras or with the dg/rpc session on worldview cameras. 

An example output from the WorldView Camera dg session: 
```<IMD>
        <NUMROWS>9107</NUMROWS>
        <NUMCOLUMNS>9961</NUMCOLUMNS>
                <BAND_P>
                    <ULLON>-121.959625500889118</ULLON>
                    <ULLAT>48.861419729316907</ULLAT>
                    <ULHAE>3261.59643554905279</ULHAE>
                    <URLON>-121.679052861405083</URLON>
                    <URLAT>48.861419729316907</URLAT>
                    <URHAE>3261.59643554905279</URHAE>
                    <LRLON>-121.679052861405083</LRLON>
                    <LRLAT>48.6797793439033981</LRLAT>
                    <LRHAE>197.97062683000695</LRHAE>
                    <LLLON>-121.959625500889118</LLLON>
                    <LLLAT>48.6797793439033981</LLLAT>
                    <LLHAE>3261.59643554905279</LLHAE>
```
Pscope rpc session output:
```   <IMD>
        <NUMROWS>2134</NUMROWS>
        <NUMCOLUMNS>6600</NUMCOLUMNS>
                <BAND_P>
                    <ULLON>86.8953303672291781</ULLON>
                    <ULLAT>27.9964617898585644</ULLAT>
                    <ULHAE>8745.40429687373035</ULHAE>
                    <URLON>87.0964457935568674</URLON>
                    <URLAT>27.9964617898585644</URLAT>
                    <URHAE>8745.40429687373035</URHAE>
                    <LRLON>87.0964457935568674</LRLON>
                    <LRLAT>27.8909457427697589</LRLAT>
                    <LRHAE>5050.42041015647828</LRHAE>
                    <LLLON>86.8953303672291781</LLLON>
                    <LLLAT>27.8909457427697589</LLLAT>
                    <LLHAE>8745.40429687373035</LLHAE>
```

**Comment by oleg-alexandrov** [comment]
I looked at both of these and also at the code. I think the lon and lat are correct, if I plot these corners, I get a rectangle, which is how it is intended. It is true that three of the four heights are the same. All these numbers are strictly speaking not that important, since it is not these that are used, rather the RPB values which are further below, so these numbers are just to make the file compliat to the expected format. I put a fix for the height though, now there should be two heights of one kind and two of the second kind. Thank you for noticing.
