### ISSUE TITLE
Sample imagery mentioned in manual does not exist anymore

### ISSUE THREAD

**Issue by bidhya** [NeoGeographyToolkit/StereoPipeline#252]
The url for the the sample stereo 053950035030_01_P001_PAN does not exist on the website linked here.
[42] Digital Globe. Satellite Imagery and Geospatial Information Products. Digital Globe sample
imagery http://www.digitalglobe.com/product-samples, . URL http://www.digitalglobe.com/
product-samples 

Do you have alternatives to this?

**Comment by ScottMcMichael** [comment]
The bad news is that they redid their website and don't offer the same image for download anymore.  The good is that it looks like they have a bunch of samples to choose from:  https://www.digitalglobe.com/samples

We'll try to redo our sample in the manual soon but until then the processing steps should be the same for one of the other Pan stereo samples.

**Comment by ScottMcMichael** [comment]
This should be updated to a current sample file in the next daily build.
21297f2d8ce95a4483612394893f1346190b0955
