### ISSUE TITLE
Unexpected results from `--save-index-map` option in `dem_mosaic` with the `--median` switch

### ISSUE THREAD

**Issue by ShashankBice** [NeoGeographyToolkit/StereoPipeline#253]
The output index map returned with the median in `dem_mosaic` option does not correspond to the index saved in the output text file.
This works for last and first options though.

**Comment by dshean** [comment]
Interesting.  

I use use this to create median timestamp products, and I the output looked OK, although I didn't test exhaustively:
https://github.com/dshean/gmbtools/blob/master/gmbtools/dem_mosaic_validtiles.py
https://github.com/dshean/gmbtools/blob/master/gmbtools/dem_mosaic_index_ts.py

I have this note about using a nonzero nodata value, and recall a discussion about an issue like this in the past: https://github.com/dshean/pygeotools/blob/master/pygeotools/lib/geolib.py#L2236

**Comment by ShashankBice** [comment]
Yeah, I have used this in the past, although the current 3 CCD workflow provides a very easy way to check this. The DEM index returned by the tool which should have been in the middle column of the DEM configuration is actually at the base of the right column. 
The 0 no data value does make sense and I checked that the tool uses a non-zero value for `--save-index-map` configuration.
Just shared data with Oleg, Scott and you.

**Comment by oleg-alexandrov** [comment]
I will look at this in a few days. Thank you for the report.

**Comment by oleg-alexandrov** [comment]
That was a bug, thank you. I put a fix. It was a bookkeeping issue in some circumstances. As a temporary work-around, you can invoke dem_mosaic with a value of --block-size larger than our output image size. The bug was showing up with --save-index-map when paired with median or nmad computation.
