### ISSUE TITLE
bundle_adjust with num-passes > 1... issue writing final condition files

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#256]
If num-passes > 1, but bundle_adjust converges quickly, the final condition files are not written.
i.e., after the first pass:
No new outliers removed, and the algorithm converged. No more passes are needed.
... then it simply writes the adjust/tsai files, without writing the final condition files (which are useful for using with pc_align).

**Comment by oleg-alexandrov** [comment]
I put a fix. Now bundle_adjust will save all residual files after each pass since it is not guaranteed to reach the last one. This is some overhead, but normally one calls this tool with maybe two or three passes. Thanks for the report.
