### ISSUE TITLE
Upgrade the documentation build system and maybe the build machine

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#260]
Our LaTeX is too old and does not support the "doi" keyword. Need to upgrade it. I am thinking the problem is even that our build machine is too old, it is centos 6, which is from 2011, so that will need to be upgraded.

I am tempted to move our build system to something more recent, say Ubuntu 16, which is released in 2016. I think Ubuntu is more mainstream nowadays and is easier to deal with packages for it.

**Comment by oleg-alexandrov** [comment]
And consider also making our documentation a set of html files accessible from search engines and hosted on our web server. I tried this with latex2html recently and results were not nice (or doc is complicated and that tool can't handle it well). Another option is https://www.sphinx-doc.org.

**Comment by rbeyer** [comment]
This issue has been addressed by 85e67c2e307da0af60f801c82d4296fc5b5c41df .
