### ISSUE TITLE
Constraint on camera height

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#271]
Add to bundle_adjust and cam_gen the option of keeping the height of camera center above the datum within a given range. Will likely improve the accuracy for cases when the camera height is known.

**Comment by ShashankPlanet** [comment]
Hi Oleg, 
This constraint is really great. I wonder if we can fix x,y position to within a certain limit as well and just try to solve for orientation ? I try doing this with bundle_adjust but the optimized orientation is very bad and the resulting ortho image is displaced by several kms....
This is the command I invoke:
`bundle_adjust -t nadirpinhole --datum WGS84 -o out_cam_cen_optimize_rotation_individual/out $test_scene test_camgen.gcp test_no_refine_at_all.tsai --translation-weight 10 --rotation-weight 0 --num-passes 1 --inline-adjustments --disable-pinhole-gcp-init`
The input camera model has correct position but wrong rotation, and using the gcps I try to force the cameras to be in place (`translation-weight 10`) and let orient it freely (`--rotation-weight 0`). The result is not what I expect and the optimized rotation is pretty similar to the starting rotation. Is there a better way to achieve this goal ?
Thanks,
Shashank

**Comment by oleg-alexandrov** [comment]
Maybe you can try to set --camera-weight to 0 as well. That is a combination of rotation and translation. Then, it may help if you have a stereo pair, with each gcp in both of the two images, for those I think we do an extra trick in moving the entire camera set to respect GCP. Then, if you have two cameras, but GCP are not shared among them one could use --transform-cameras-using-gcp. 

Regarding adding new logic to fix the x, y, z position to within a certain range, maybe I can get to it later this summer.

**Comment by oleg-alexandrov** [comment]
This was implemented, tested, and documented as the cam_gen option --cam-height (together with --cam-weight to keep the weight).  A bug was also fixed in camera center determination, when an input camera exists so one does not start with just four corners on the ground.
