### ISSUE TITLE
Move from libLAS to PDAL

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#278]
The libLAS page (https://liblas.org/) says that it has been superseded by PDAL and hence it is in hibernation mode. PDAL has support for newer version 1.4 of LAS, and, unlike libLAS it has a conda-forge package.

libLAS also does not build with latest cmake and apparently with newer gdal, and liblas does not support C++-11, but there are patches for that: https://github.com/libLAS/libLAS/issues/140.

I looked at where we use libLAS in ASP (to read and write las files) and it looks like little work to switch. Here's a guide:

https://pdal.io/api/transition/index.html

This transition will make it easier to offload our dependencies to conda-forge.

**Comment by oleg-alexandrov** [comment]
This will help with the following error I encountered with a recent las file: "version minor out of range". That is because LibLas and hence ASP presumably does not support newer versions of the LAS format, being in hibernation mode, which PDAL should.  A workaround for this should be for now to use pdal_translate --writers.las.minor_version=2 to downgrade the LAS file.

**Comment by AndrewAnnex** [comment]
I actually just ran into issues surrounding using gdal and rasterio in a conda environment with ASP, so I would really like to see this change

**Comment by oleg-alexandrov** [comment]
The move to PDAL was completed last year. As of recently can save to las the triangulation error, image intensity, and horizontal and vertical uncertainties.
