### ISSUE TITLE
ISIS3.8 Data Area and ASP Examples

### ISSUE THREAD

**Issue by jlaura** [NeoGeographyToolkit/StereoPipeline#281]
Historically, the ISIS data has never been kept under explicit version control. New kernels have been added and/or moved as needed. We are actively working to get the data area under version control [#531](https://github.com/USGS-Astrogeology/ISIS3/issues/351), [#3239](https://github.com/USGS-Astrogeology/ISIS3/issues/3239), and [#3282](https://github.com/USGS-Astrogeology/ISIS3/issues/3282).

With the release of ISIS 3.8.1, we have updated the ISIS data area. Here is [a link](https://github.com/USGS-Astrogeology/ISIS3/pull/3283) to the PR where the issues encountered and fixes are enumerated. Using an ISIS version < 3.8.0 with the new data area will result in issues for:

### Known Applications Impacted:
(Certain Mars calibration programs)
- mical
- moccal
- mocproc
- ctxcal
- hical
- hicalbeta
- hicalproc
- thmbasemap1
- thmproc

### Known Sensor Models Impacted:
  - CTX
  - MOC
  - HiRISE
  - THEMIS
  - Anything else ISIS supported that uses SPICE and collected Mars data

So, [this line](https://github.com/NeoGeographyToolkit/StereoPipeline/blob/e91bcf580426b04e9fdd7b55b92f95e8dcd6a038/examples/CTX/Makefile#L15) in your example will fail if the user is keeping up to date on their data, but not on their ISIS version (or any other permutation where the data != code). 

As I said above, we are working on versioning the data too, but in the short term, this is likely to be an issue that we all see coming in from users.

**Comment by oleg-alexandrov** [comment]
Thanks, this is good to know. It does make sense that old code can't handle new data. Hopefully when the dust settles down on the many changes ISIS undergoes the coupling need not be so tight, so say new software can still read old data, or at least give a meaningful error message. I will keep this in mind.

**Comment by rbeyer** [comment]
When ASP 2.7.0 gets released, it will be compiled against a more recent ISIS release, and a more recent reference ISIS data area.  We only make ASP releases approximately annually, and with the rapid rate of change in ISIS, we're just going to be behind.

However, as Jay indicates, the problem isn't really related to how fast the ISIS codebase is moving, but the fact that the ISIS data area is not versioned.  This is a known issue for ISIS, and something that they are working to attempt to get solved.
