### ISSUE TITLE
make a new release due to isis3 spice kernel changes?

### ISSUE THREAD

**Issue by AndrewAnnex** [NeoGeographyToolkit/StereoPipeline#284]
I recently ran into the various spice kernel related issues with isis3 (https://github.com/USGS-Astrogeology/ISIS3/issues/3433 and related) that I was able to fix with the patch from commit 8a886d515b8301009ab15b115883195467af698b after some head scratching. I *think* it would be best to make a new release to work against isis3 3.8.1 until the usgs makes the kernels compatible with older isis3 versions (something I saw a reference to but not completed yet?).

**Comment by AndrewAnnex** [comment]
I see #281 links to this

**Comment by jlaura** [comment]
We are releasing 3.9.0 today, so if peeling a new ASP release, probably best to target that.

**Comment by AndrewAnnex** [comment]
I'll close this issue as it seems to have been fixed/on everyone's radar
