### ISSUE TITLE
corr-search window in stereo.default.example is strange

### ISSUE THREAD

**Issue by rbeyer** [NeoGeographyToolkit/StereoPipeline#285]
The line in our stereo.default.example is

`# corr-search -80 -2 20 2`

I know it is commented out, and I know it's been like that for 8 years.  However, is that really a good window?  Seems really small.  I know that we have it commented out to encourage people to leave it like that and let the software guess a good value for corr-search.

However, if someone were playing around, and uncommented that line (without knowing what they were doing), is that really the best 'generic' value for corr-search?  If not, we should change it to something more reasonable.

**Comment by oleg-alexandrov** [comment]
This window is not small if the images are well-aligned, such as with epipolar alignment, when the disparity is mostly in x. Most stereo software assumes then that there is no disparity in y to start with. And here the disparity in x is 20 pixels. For a shot of Pluto this likely could be too much given the distance to the planet. The more accurate answer is that I have seen disparities going all the way to thousands of pixels, so there is no rule that applies. The users are on their own when messing up with this. You are welcome to put some numbers that you like better, or add a comment above mentioning the issues.

**Comment by rbeyer** [comment]
Fair enough.
