### ISSUE TITLE
Common ip_detection algorithm for bundle_adjust, stereo and ipfind

### ISSUE THREAD

**Issue by ShashankBice** [NeoGeographyToolkit/StereoPipeline#286]
Right now, bundle_adjust, stereo and ipfind all detect interest points using different methods, resulting in varying ip distribution using similar parameters for all these methods. The ip detection is currently working the best for bundle adjustment. 
While doing stereo, this becomes an issue, as the ip detected for images lacking large scale features is very less. This is many a times handled with using match-file from bundle adjustment, but this work around does not help when using map projected images for stereo. 
It would be nice to have the ip detection algorithm in the same way across these 3 programs :)

**Comment by oleg-alexandrov** [comment]
You can see if the new --matches-per-tile parameter works for you. (https://stereopipeline.readthedocs.io/en/latest/stereodefault.html) 

This should work with both stereo and bundle adjustment, with and without mapprojection.
