### ISSUE TITLE
Standalone point cloud erode?

### ISSUE THREAD

**Issue by foobarbecue** [NeoGeographyToolkit/StereoPipeline#288]
It's nice that dem_mosaic and point2dem have "erode" options which remove points from the edges of clouds.

I would like to do that to my point clouds before aligning several clouds using pc_align or n_align.

Is it possible to just run erode?

**Comment by oleg-alexandrov** [comment]
No, we provide no facilities to erode points clouds by themselves. You
could try to convert them to las with point2las and look for any tools that
process this format (there should be some, as it is a pretty widespread
format). Then point2dem or pc_align could use your cleaned up las file.

**Comment by foobarbecue** [comment]
I think the reason I felt I needed this was possibly because of spurious points caused by what's happening in #302

**Comment by oleg-alexandrov** [comment]
Just for the record putting here a small comment I put at that issue as well. You can try to nip this in the bud, so to speak, by doing erosion at stereo_fltr stage, with --erode-max-size. That one at some point we should make positive as the default.

**Comment by oleg-alexandrov** [comment]
(And this does not mean all stereo must be redone, just the fltr step and what comes next, so one should use stereo -e 3 to resume at this step.)

**Comment by oleg-alexandrov** [comment]
I added to point2las the ability to filter out points by triangulation error, as for point2dem. That should help a bit with filtering the cloud, and then the las file can be passed to pc_align. Note quite what asked, but a step on the way.
