### ISSUE TITLE
pc_align rotation + vertical translation only

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#297]
I have several applications where it would be useful to align point clouds by rotation and vertical translation only... i.e. no horizontal translation. Could something like this be possible?

... it could be useful aligning DEMs in flat regions, especially if they are well-registered horizontally to the Earth's surface, but contain ramps.

**Comment by oleg-alexandrov** [comment]
That would be tricky. We use libpointmatcher to do the work, and it does not support that. I hacked into it to support translation only, and now that's a patch we have to maintain. I would be reluctant to add to that. There should be standalone python alignment tools which may be able to easier to hack into, e.g., https://github.com/dshean/demcoreg

**Comment by jchollingsworth** [comment]
Ok... Thanks :)
