### ISSUE TITLE
geodiff replacing nodata value of 2nd DEM with Nan in output

### ISSUE THREAD

**Issue by adehecq** [NeoGeographyToolkit/StereoPipeline#301]
It seems like geodiff replaces dem2 nodata values with NaN and never set them back to the original no data value (geodiff.cc, line 155 onwards).
Would it be possible to fix this?

**Comment by oleg-alexandrov** [comment]
I never saw this before. Do your own DEMs that you try to diff have NaN anywhere? In either way we could fix it, but it would help to know the answer to this.

**Comment by oleg-alexandrov** [comment]
I was able to verify this with my own data. I have an idea where that is coming from, I think it should be in geotransform, but that is in widespread use, so I'd rather fix it in geodiff and see if we ever get bitten by it in some other place. 

Thank you for the report. I pushed the change. But our daily build is broken, with no resources to fix it, so it will take a while until this will be reflected in the latest build.

**Comment by adehecq** [comment]
Oleg,
Sorry for the late reply, I should setup GitHub notifications properly because I wasn't aware of your reply...
Thanks for fixing it and let me know when the daily build will be updated.

**Comment by oleg-alexandrov** [comment]
Amaury, our daily build is broken, and it would take some time and effort
to bring it back, given that we have no resources to do ASP development in
the next several months. Also, our daily build server is down for
mysterious reasons. Sorry. If you do need a build with that fix, we can
provide you a link to a custom build shared via Google drive (which Scott
made to fix some other problem, incorporating my fix which is older along
the way).
