### ISSUE TITLE
Spurious MGM disparity if D_sub.tif is invalid

### ISSUE THREAD

**Issue by ShashankBice** [NeoGeographyToolkit/StereoPipeline#308]
If for some reason the D_sub.tif fails to compute in the stereo_pprc step in SGM/MGM (characterised by warning: "unable to compute a valid search range for SGM input"), the correlation step goes on with search range of 0,0 and produces disparities which are way less than actual disparities (in the order of few pixels). The resulting DEM is complete (no holes) but the height values are off by several meters (due to wrong disparities).  Ideally the process would stop if an empty D_sub.tif is encountered.

**Comment by oleg-alexandrov** [comment]
In the meantime the logic for finding interest point matching with mapprojected images changed and now happens at full resolution. In my experience, now even areas with a huge amount of clouds get at least some interest points, as clouds and real terrain don't get mixed together as easily as when the resolution is reduced. 

So, the initial search range should be fine, I hope. If not having any luck, I can take a look at a specific example. For now I am closing this.
