### ISSUE TITLE
Median Filter in point2dep

### ISSUE THREAD

**Issue by MiladGhorbaniG** [NeoGeographyToolkit/StereoPipeline#318]
Hi, I'm using ```asp 2.7.0```. I created point clouds. I tried to generate DEM with median filter, but different values of window size and threshold have no effect on the result.
```
point2dem results/run-PC.tif --median-filter-params 11  40 -o stereo/image \
--nodata-value -10000 -n
```

**Comment by oleg-alexandrov** [comment]
The point of this switch --median-filter-params switch is to remove large
outliers, like spikes, using a median filter (points that are too different
from the median will be wiped). Unless your DEM has those spikes it won't
be affected.

If you would like the points in the cloud that end up forming the grid
heights to not be processed using a weighted average when binning, but to
simply pick the median in each bin, you should use --filter median.

**Comment by MiladGhorbaniG** [comment]
Thanks for the fast answer at the weekend. I will test that.
