### ISSUE TITLE
Put ASP version number in log files

### ISSUE THREAD

**Issue by rbeyer** [NeoGeographyToolkit/StereoPipeline#319]
**Is your feature request related to a problem? Please describe.**
In the many .txt log files that ASP writes out, we promptly run uname and paste the output there, but there does not seem to be a record of what ASP version number is being used.

**Describe the solution you'd like**
Include the ASP version number in the logfile output.

**Comment by oleg-alexandrov** [comment]
Done. Now at the top of each log file there is the line:

ASP 2.7.0

with the version being pulled from the appropriate CMake file.
