### ISSUE TITLE
Proj4 Errors with point2dem

### ISSUE THREAD

**Issue by jlaura** [NeoGeographyToolkit/StereoPipeline#326]
**Describe the bug**
Proj4 errors in point2dem 

**To Reproduce**
1. Pre-process using ISIS as per the manual, bundle adjust using ASP's capabilities.
1. Generate a CTX PC. We used images: F21_043907_1652_XN_14S184W and F21_043841_1654_XN_14S184W.
1. Run point2dem asking for an orthographic projection: 
`point2dem --threads 14 --dem-spacing 20 --datum MOLA --orthographic --nodata -32767 results_ba/F21_043907_1652_XN_14S184W__F21_043841_1654_XN_14S184W-PC.tif -o results_ba/F21_043907_1652_XN_14S184W__F21_043841_1654_XN_14S184W`
1. We then see the following output:
```
2020-12-09 13:53:02 {0} [ console ] :   --> Re-referencing altitude values using datum: D_MARS.
2020-12-09 13:53:02 {0} [ console ] :       Axes [3.396e+06 3.396e+06] meters.
2020-12-09 13:53:40 {0} [ console ] : Bad projection in GeoReference.cc. Proj.4 error: tolerance condition error.
Location is Vector2(175.268,-15.1453).
```

**Expected behavior**
With other pairs is working without an issue. This does not look like a longitude issue (we are not defining center lat or center lon) as we have other pairs on either side working as expected.

Question: Do we need to be defining the center lat and center lon? If not, what do you all default to? 0,0 or 0,180? 

If we swap the projection to something like mercator, this works as expected. Also, setting the center lat/ center lon also seems to have solved our issue. So I think this might be a question of - what defaults are being used?

**Error Logs, Terminal Captures, Screenshots**

**Your Environment (please complete the following information):**
 - OS: CentOS7
 - ASP Version:2.7.0
- Any other environment information that might be helpful?

**Additional context**

**Comment by oleg-alexandrov** [comment]
Thank you for the report. I must say I never used the orthographic projection, that probably explains your issue.

Would the stereographic projection work for you? Then you would need to specify --proj-lon and --proj-lat with --stereographic.

**Comment by oleg-alexandrov** [comment]
I believe I recently fixed a similar error to what is here. GDAL was throwing an exception for a point it could not handle which wasn't caught on our side. Now it is caught and the point skipped.
