### ISSUE TITLE
docs: "on page"

### ISSUE THREAD

**Issue by foobarbecue** [NeoGeographyToolkit/StereoPipeline#328]
There are a couple of places where the docs refer to a "page" but don't have a page number. Presumably these should be references. I can volunteer to fix it later but just wanted to record the issue so I don't forget.

https://github.com/NeoGeographyToolkit/StereoPipeline/blob/3a2b03cebd8373da37fa28cb2da4f7e177e8093a/docs/bundle_adjustment.rst#L699

https://github.com/NeoGeographyToolkit/StereoPipeline/blob/3a2b03cebd8373da37fa28cb2da4f7e177e8093a/docs/tools/cam2map4stereo.rst#L14

**Comment by oleg-alexandrov** [comment]
Thank you. I put a quick fix for these by just referring to the Tutorial, where these are discussed. Here's my fix: https://github.com/NeoGeographyToolkit/StereoPipeline/commit/6e37182a98903a4362e837ac716de3578ba072f5

One can be more specific by actually providing a link or a reference in both cases. If you are familiar with .rst syntax and feel that it would be helpful, you are very welcome to give it a try and make a pull request. I can verify later if the resulting changes work as intended.
