### ISSUE TITLE
libgnomevfs-2.so.0 undefined symbol g_mutex_lock error

### ISSUE THREAD

**Issue by jaigsingla** [NeoGeographyToolkit/StereoPipeline#330]
Hello,

Facing libgnomevfs-2.so.0 undefined symbol g_mutex_lock error on Linux 7 with stereopipeline 2.6.2 while using stereo_gui.

regards,
Jai

**Comment by oleg-alexandrov** [comment]
I assume this is Red Hat Enterprise Linux 7. 

I wonder if you can try the latest ASP and see if it works better for you. It can be accessed here: https://byss.arc.nasa.gov/stereopipeline/daily_build/ It needs to be extracted in your home directory and run from there, so without any installation.

At some point I included more libraries with the ASP we ship, and maybe it fixes it. 

If that does not work, you can try fetching ASP with conda, as described here

https://stereopipeline.readthedocs.io/en/latest/installation.html

in section 2.3.
