### ISSUE TITLE
opticalbar: distorted results

### ISSUE THREAD

**Issue by metzm** [NeoGeographyToolkit/StereoPipeline#337]
**Describe the bug**
We are experiencing problems with stereodem extraction from declassified satellite images kh 4b.
The problem is that edges of the result are shifted by several km towards the center of the image, as if the panorama correction is not working properly.

**To Reproduce**
Follow the example in https://stereopipeline.readthedocs.io/en/latest/examples.html#declassified-satellite-images-kh-4b
with DS1043-2201DA006, DS1043-2201DF006.
Providing 34 evenly spaced GCPs to bundle_adjust did not improve the results.

**Expected behavior**
The geolocation of the result is similarly accurate across the whole scene without distortions at the far edges.

**Your Environment (please complete the following information):**
 - OS: Linux Fedora 34, Centos 7
 - ASP Version: 2.7.0

**Comment by oleg-alexandrov** [comment]
Thank you for letting us know. ASP's support for KH cameras is rather experimental. There is film warping that we don't model, and it is an open question about how well we model the cameras or solve for them given the model. It will take a good amount of work for us to improve the support for these cameras, and for the time being we have no funding for this. 

Maybe things may work better for smaller sections of the images, so mosaicking just one or two observations.

**Comment by metzm** [comment]
The example in the manual recommends a sanity check: mapproject the images with these cameras before proceeding with stereo processing. Interestingly, the result of mapproject is very good and it appears that correction for the KH panorama cameras is properly applied. It seems that this panorama correction is missing in the stereodem. Maybe this helps to narrow down any efforts for improvement.

**Comment by neteler** [comment]
> Thank you for letting us know. ASP's support for KH cameras is rather experimental. There is film warping that we don't model, and it is an open question about how well we model the cameras or solve for them given the model. It will take a good amount of work for us to improve the support for these cameras, and for the time being we have no funding for this.

Do you have any estimate what range of funding might be required here? Please feel free to answer via [email to me](https://www.mundialis.de/neteler/).

**Comment by oleg-alexandrov** [comment]
BTW, a paper on related work for KH-4 is being published. (https://arxiv.org/pdf/2201.07756.pdf) They model rigorously the optical bar sensor but do not deal with the distortion due to film scanning.
