### ISSUE TITLE
incorrect IP matches when running Bundle adjust with mapprojected data

### ISSUE THREAD

**Issue by Adabian** [NeoGeographyToolkit/StereoPipeline#341]
I am a beginner of ASP, recently i am trying to build DEM through this software. I use LROC NAC images with different illumination conditions and i want to run bundle adjust for each pairs at first. In this step, I will often meet this situations,it fail when i use original images(unmapprojected images) only.This step reports error:VW Error:Expected 2 cameras but crn has 0.I check that and find ip numbers does not reach the min matches(30).In the ASP book, I find that we can  add ip matches for mapprojected images and use --mapprojected data option for bundle_adjust. Well,i add 5 ip for mapprojected images,after i run ba for original images use the option above,i check .match in Stereo_gui and it's not correct in original images. Another thing makes me confused is that it doesn't report errors during ba.I am not sure how to check if the ba process is accurate. Should i check this profile run_final_residuals_loss_function_raw_pixels.txt? How much residual is qualified?
Here are my commands:
   1.mapporject ref_dem.tif A.cub A_proj.tif
      mapporject ref_dem.tif B.cub B_proj.tif
   2.stereo_gui A_proj.tif  B_proj.tif run/run                            (  i add 5 ip match)
   3.bundle_adjust A.cub B.cub --datum Moon --min-matches 1 -o run/run --mapprojected-data ' A_proj.tif  B_proj.tif ref_dem.tif'
   4.stereo_gui A.cub B.cub  run/run                     ( the ip matches do not match each other in original images)
Hope u to point out my mistake .Thanks a lot.

**Comment by Adabian** [comment]
Hi,oleg
I tried again and it was still not correct.The version of mine is 2.6.1.
I posted my mapprojected images IP matches below.
![clipboard](https://user-images.githubusercontent.com/83965299/137617759-4ab9145a-aa85-4b7f-acca-7808a6ca2877.png)

There were 8 IP matches i manually added.
after step 4, i checked the run-A__B.match
![clipboard2](https://user-images.githubusercontent.com/83965299/137617861-5e909a04-aa5e-4601-9943-dd55f8930d38.png)

I checked each IP matches and not matched. It seems that --mapprojected option does not work. 
Well, the transform from mapprojected space to image space is not clear for me. Would the format of mapprojected image(.tif) influence the transform?

**Comment by oleg-alexandrov** [comment]
I see. 

When you run bundle adjustment and stereo (in fact, you can skip stereo for now), you should look carefully everywhere in the log (what it prints in the terminal) about whether it writes new match files or uses an existing (cached) match file.  It should reuse matches. I hope it does not get confused somehow and creates its own matches. 

The transform from mapprojected space to image space is the following. For each mapprojected pixel (i, j), its longitude and latitude is found, and from there the xyz position on the ground is found using the DEM, then xyz is projected into the camera. In short, you go from ground pixel to image pixel. 

You can also try ASP 3.0.0, your version is kind of old, though I am not sure if we fixed anything there. 

If no luck, you can share with me all your data (.cub files, mapprojected file, DEM file, the two match files) and I will take a look. This should be reproducible on a very small clip so one does not need to share a 1 GB cub file.

I hope you also wipe any existing directories if trying this again. 

And just repeated the map projection and bundle adjustment logic (no stereo) and it again works. Here's what bundle adjustment prints out for me, and hopefully you can compare with your own log. 

bundle_adjust --datum D_MOON --min-matches 1 -o run/run M134980177LE.cal.echo.cub M1160064736LE.cal.echo.cub --mapprojected-data 'M134980177LE.cal.echo.map.tmp.tif M1160064736LE.cal.echo.map.tmp.tif tmp.tif'  
Loading DEM: tmp.tif
        --> Using cached match file: run/run-M134980177LE.cal.echo.map.tmp__M1160064736LE.cal.echo.map.tmp.match
Reading: run/run-M134980177LE.cal.echo.map.tmp__M1160064736LE.cal.echo.map.tmp.match
Saving 2 matches.
Writing: run/run-M134980177LE.cal.echo__M1160064736LE.cal.echo.match

Then I verified that the new match files aligned well with the original images.
