### ISSUE TITLE
match file parsing lib and convert tool

### ISSUE THREAD

**Issue by PicoJr** [NeoGeographyToolkit/StereoPipeline#350]
Hello,

I wrote a [Rust lib](https://github.com/PicoJr/aspmatch) for parsing [ASP match files](https://stereopipeline.readthedocs.io/en/latest/outputfiles.html?highlight=match#guide-to-output-files).

It provides functions for parsing and writing ASP match files as binary or text.

It also contains a `convert` tool provided as an example similar to [parse_match_file.py](https://stereopipeline.readthedocs.io/en/latest/tools/parse_match_file.html) cf [examples](https://github.com/PicoJr/aspmatch#examples).

> `convert` **does** parse descriptors

motivation: it has been a while I wanted to write a binary parser using [nom](https://github.com/Geal/nom). I thought I might as well write something useful =)

NB: I have not published my code to [crates.io](https://crates.io/) (Rust registry) yet so `aspmatch` is not cast in stone (I can still change the name).

**Comment by oleg-alexandrov** [comment]
Hope that was fun and instructive.
