### ISSUE TITLE
Follow processing DG raw images tutorial but results are problematic

### ISSUE THREAD

**Issue by jiangye-dm** [NeoGeographyToolkit/StereoPipeline#351]
**Describe the bug**
Follow Section 4.1 in the user's guide. Download the system-ready Stockholm image. Run stereo. It runs fine. But the result seems weird (see attached image of out-PC.tif). In the created DEM tif all pixels are 255

**To Reproduce**
1. Download system-ready Stockholm images from https://resources.maxar.com/optical-imagery
2. Follow the instruction in Section 4.1 and run 
```
stereo -t dg --subpixel-mode 1 --alignment-method affineepipolar \
    Stockholm_System-Ready_Stereo_50cm/056082198020/056082198020_01_P001_PAN/12FEB16101327-P1BS-056082198020_01_P001.TIF \
    Stockholm_System-Ready_Stereo_50cm/056082198020/056082198020_01_P001_PAN/12FEB16101426-P1BS-056082198020_01_P001.TIF \
    Stockholm_System-Ready_Stereo_50cm/056082198020/056082198020_01_P001_PAN/12FEB16101327-P1BS-056082198020_01_P001.XML \
    Stockholm_System-Ready_Stereo_50cm/056082198020/056082198020_01_P001_PAN/12FEB16101426-P1BS-056082198020_01_P001.XML dg/out
```
3. Create DEM
```
point2dem dg/output-PC.tif
```

**Expected behavior**
DEM similar to Figure 4.1

**Error Logs, Terminal Captures, Screenshots**
Show out-PC.tif 
<img width="546" alt="Screen Shot 2021-12-01 at 1 37 11 PM" src="https://user-images.githubusercontent.com/73143468/144320862-c92ac829-8657-40e9-84f9-1f66d290eebd.png">

**Your Environment (please complete the following information):**
 - OS: macOS
 - ASP Version: 3.0.0

**Comment by oleg-alexandrov** [comment]
It is not possible for the DEM to have only the values of 255. Sure you can get junk, not not 255 throughout. 

Try to do gdalinfo -stats on your DEM and share the results. Or you can open the DEM in stereo_gui then then hillshade it. It is likely some mistake in visualization somewhere.

**Comment by jiangye-dm** [comment]
Does the out-PC.tif look normal? Here is output of gdalinfo

Driver: PNG/Portable Network Graphics
Files: /Users/jiangye/Projects/SatStereo/dgsample/out.png
Size is 3635, 2877
Coordinate System is `'
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 2877.0)
Upper Right ( 3635.0,    0.0)
Lower Right ( 3635.0, 2877.0)
Center      ( 1817.5, 1438.5)
Band 1 Block=3635x1 Type=Byte, ColorInterp=Gray
  Minimum=255.000, Maximum=255.000, Mean=255.000, StdDev=0.000
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=255
    STATISTICS_MINIMUM=255
    STATISTICS_STDDEV=0
    STATISTICS_VALID_PERCENT=100

**Comment by jiangye-dm** [comment]
I just noticed by running ```point2dem dg/output-PC.tif```, it creates out.obj, out.png and out.mtl. There is no tif created. Does out-PC.tif (showed above) looks normal?

**Comment by oleg-alexandrov** [comment]
You may have ran point2mesh instead of point2dem. If you are very sure you ran point2dem, you can try deleting your build and getting a new one from https://github.com/NeoGeographyToolkit/StereoPipeline/releases.

Our own very lengthy daily regression with the latest build runs fine and point2dem produces lots of valid DEMs in Tif format.

**Comment by jiangye-dm** [comment]
I did mistakenly use point2mesh. I changed to point2dem and it generates valid DEM. Thank you!
