### ISSUE TITLE
Is there a way to get camera pose (position and orientation) from RPC images

### ISSUE THREAD

**Issue by jiangye-dm** [NeoGeographyToolkit/StereoPipeline#352]
By running stereo, it reports the distance between camera centers. Is camera pose estimated and stored somewhere?

**Comment by oleg-alexandrov** [comment]
The distance between camera centers for RPC is actually bogus (I put it on my to-do list to hide that at some point). 

We regretfully have no way of knowing where the camera was. I guess the camera pose for RPC could be estimated, at least for pinhole cameras (such as SkySat), but we don't do that. Note also that many times the RPC approximates a linescan camera (such as for Digital Globe and Pleiades), and then the camera pose varies as the satellite moves in the sky while acquiring image lines.

**Comment by jiangye-dm** [comment]
Thanks for the explanation.
