### ISSUE TITLE
How to use GPU to speed up the processing of ASP

### ISSUE THREAD

**Issue by zhaomumu233** [NeoGeographyToolkit/StereoPipeline#354]
I would like to inquire whether ASP supports GPU acceleration and if so, how to set it up. I would be grateful if you could answer my confusion.

**Comment by oleg-alexandrov** [comment]
No, ASP does not support GPUs and there are no plans to do so. We suggest using a machine with many CPU cores, or many such machines on a network with shared storage.

**Comment by zhaomumu233** [comment]
Thank you for answering my confusion~
