### ISSUE TITLE
mapproject --version doesn't work as expected

### ISSUE THREAD

**Issue by rbeyer** [NeoGeographyToolkit/StereoPipeline#357]
**Describe the bug**
When I run `mapproject --version` I get a usage statement and not the version number.

**To Reproduce**

```
$> mapproject --version
usage: mapproject [options] <dem> <camera-image> <camera-model> <output-image>
Instead of the DEM file, a datum can be provided, such as
WGS84, NAD83, NAD27, D_MOON, D_MARS, and MOLA.

optional arguments:
  -h, --help            show this help message and exit
[... listing of arguments truncated ...]
  -v [ --version ]             Display the version of software.
  -h [ --help ]                Display this help message.
usage: mapproject [options] <dem> <camera-image> <camera-model> <output-image>
Instead of the DEM file, a datum can be provided, such as
WGS84, NAD83, NAD27, D_MOON, D_MARS, and MOLA.
mapproject: error: Missing input DEM.
$>
```

It is odd that it repeats the short usage both before and after the arguments listing, and finally complains about the missing required DEM argument.

**Expected behavior**
I'd expect behavior identical to `stereo --version`

**Your Environment (please complete the following information):**
 - OS: Linux
 - ASP Version:StereoPipeline-3.0.0-2021-12-30-x86_64-Linux

**Comment by oleg-alexandrov** [comment]
I put a fix. I also tested bundle_adjust, parallel_bundle_adjust, stereo, and parallel_stereo. Those worked, but for some this option was not documented, so I fixed that too.
