### ISSUE TITLE
parallel_stereo with asp_mgm `/bin/sh: free: command not found`

### ISSUE THREAD

**Issue by dshean** [NeoGeographyToolkit/StereoPipeline#364]
**Describe the bug**
Running parallel_stereo with asp_mgm on latest daily build with sample frame camera images and RPC session.  Each tile produces:
>/bin/sh: free: command not found
>Warning: Error checking system memory, skipping the memory test!

**To Reproduce**
`parallel_stereo --stereo-algorithm asp_mgm --corr-kernel 7 7 *pan.tif mgm_rpc/mgm_rpc`

**Expected behavior**
I think this is all just for SGM/MGM memory consumption estimate, which I know was somewhat experimental.  Don't want to assume `free` utility is installed by default.

**Your Environment (please complete the following information):**
 - OS: [e.g. macOS, Linux, and their version number]
 >Darwin  19.6.0 Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64 x86_64 i386 iMacPro1,1 Darwin
 - ASP Version: [e.g. 2.6.2, can find via `stereo --version`]
> NASA Ames Stereo Pipeline 3.0.1-alpha
>   Build ID: 39a1cf2e
>   Build date: 2022-04-27
> 
> Built against:
>   NASA Vision Workbench 3.0.0
>     Build ID: a717c7e2
>   USGS ISIS 5.0.1
>   Boost C++ Libraries 106800
>   GDAL 2.4.1 | 20190315

**Comment by oleg-alexandrov** [comment]
Since when do you expect anything 'free' on the Mac? Or even cheap?

I put a fix in https://github.com/NeoGeographyToolkit/StereoPipeline/commit/11fae82909f6434556132faebd249d0d198c54ba. 

Thanks. The moral: Use Linux.
