### ISSUE TITLE
disparitydebug: Mismatch between docs and actual command line options

### ISSUE THREAD

**Issue by dpmayerUSGS** [NeoGeographyToolkit/StereoPipeline#368]
**Describe the bug**
There appears to be a mismatch between the command line options listed in the [online documentation for `disparitydebug`](https://stereopipeline.readthedocs.io/en/latest/tools/disparitydebug.html) and the options that the program actually accepts. As far as I can tell, the options listed when running `disparitydebug -h` are complete and accurate. 

The information in RTD states that `disparitydebug` accepts an option called `--float-pixels`, but invoking the program with this option generates an "unrecognized option" error message. I can't find this option listed in the [source code for disparitydebug.cc](https://github.com/NeoGeographyToolkit/StereoPipeline/blob/05432a55b4a1108febc5c3a999159e330ba1b2a1/src/asp/Tools/disparitydebug.cc#L161-L174) either. 

RTD states there is also an option `--input-file`, which does *not* appear in the list of options when running `disparitydebug -h`, and I can't find it in the source code, *but* running `disparitydebug --input-file somefile.tif --output-prefix some_outprefix` works as expected.  

**Expected behavior**
The command line options in RTD are a complete list of the supported options for `disparitydebug` and the options listed on RTD match the options listed when the program's help is invoked with the `-h` flag.

**Error Logs, Terminal Captures, Screenshots**
```
user@examplehost:$ disparitydebug -h
Usage: /path/to/ASP/libexec/disparitydebug [options] <input disparity map>

  [ASP 3.1.0]
  Build date: 2022-05-18

  --normalization arg (=auto)  Normalization range. Specify in format: hmin
                               vmin hmax vmax.
  --roi arg (=auto)            Region of interest. Specify in format: xmin ymin
                               xmax ymax.
  --save-norm                  Save the norm of the disparity instead of its
                               two bands.
  --save-norm-diff             Save the maximum of norms of differences between
                               a disparity and its four neighbors.
  --output-prefix arg          Specify the output prefix.
  --output-filetype arg (=tif) Specify the output file type.

  --threads arg (=0)           Select the number of processors (threads) to
                               use.
  --tile-size arg (=256, 256)  Image tile size used for multi-threaded
                               processing.
  --no-bigtiff                 Tell GDAL to not create bigtiffs.
  --tif-compress arg (=LZW)    TIFF Compression method. [None, LZW, Deflate,
                               Packbits]
  -v [ --version ]             Display the version of software.
  -h [ --help ]                Display this help message.

```
**Your Environment (please complete the following information):**
 - OS: CentOS (although issue is platform-independent)
 - ASP Version: 3.1.0

**Comment by oleg-alexandrov** [comment]
David, thanks. I fixed the doc page at https://stereopipeline.readthedocs.io/en/latest/tools/disparitydebug.html. I did not add some of the more advanced options from the tool help page (such as --save-norm or  --save-norm-diff) as those are some options I added for some specific purpose and likely have no general use.
