### ISSUE TITLE
Missing bands in D.tif with parallel_stereo

### ISSUE THREAD

**Issue by adehecq** [NeoGeographyToolkit/StereoPipeline#369]
**Describe the bug**
We discussed this Oleg, but since the latest release, D.tif files generated by parallel_stereo (that are actually a VRT file pointing to individual tile results) have gaps. See the example below:

![image](https://user-images.githubusercontent.com/3285905/177580491-8656c255-2e73-45a0-b989-9bdd2fa51399.png)

**To Reproduce**
This should work with any input image processed with parallel_stereo that has a size larger than the --corr-tile-size. In case this matters, I used nadirpinhole models with map-projected images.

**Expected behavior**
There should not be any gaps in the D.tif file (see fix below).

**Your Environment (please complete the following information):**
 - OS: macOS
 - ASP Version: 3.1.1-alpha (but the issue shows up already at 3.0.1)

**Additional context**
I managed to fix the issue manually by editing the VRT file. The sizes of the individual sizes reported is always the same as corr-tile-size, but it ignores the buffer around each tile. For example, line
\<SourceProperties RasterXSize="5000" RasterYSize="5000" DataType="Float32" BlockXSize="256" BlockYSize="256"/>
Should be
\<SourceProperties RasterXSize="5512" RasterYSize="5512" DataType="Float32" BlockXSize="256" BlockYSize="256" />
With a buffer of 512 pixels.

Here is the result with the fixed VRT file.
![image](https://user-images.githubusercontent.com/3285905/177582693-d81e6b68-30e4-4faf-a67d-9589b3b4f7e7.png)

I don't know if that can impact the rest of parallel_stereo? The RD.tif files seem complete.

I will send a link to download the example data as soon as I get a better internet connection.

**Comment by dshean** [comment]
This looks familiar, though I seem to remember seeing gaps in the D_sub.tif - is that true for your case @adehecq?

**Comment by oleg-alexandrov** [comment]
I think these are different issues and as I recall I fixed David's one. I
will be back on vacation next week and will look at the D.tif problem. Note
that F.tif should be fine though.

**Comment by adehecq** [comment]
Here's [the link](https://filesender.renater.fr/?s=download&token=5e5b440a-b7e5-4aa0-8796-a32e19b6e853) to download sample data set (valid until August 6).

Yes, I think it's only a visualization issue, but might be good to check. I don't know how the VRT file is created within ASP, but it looks like it's just an issue in the content of the file, so should be easy to fix.

**Comment by adehecq** [comment]
I quickly compared to a file created by version 3.0.0, and actually what changed since the update is the added lines:
\<SourceProperties RasterXSize="5000" RasterYSize="5000" DataType="Float32" BlockXSize="256" BlockYSize="256"/>

With these lines deleted, the band artifacts also disappear.

**Comment by adehecq** [comment]
Oh ok. Then, as I suggested, try replacing the RasterXSize and RasterYsize with the actual tile size (with buffer) rather than the corr-tile-size value. This fixed the issue on my test case.

**Comment by oleg-alexandrov** [comment]
I put a fix. It will be in tomorrow's build. I verified that gdal_translate now extracts correctly the bands from D.tif.

I also took a look one more time at David's issue with D_sub and the code looks consistent with that unrelated problem being fixed.

**Comment by dshean** [comment]
Great!  Thanks.

**Comment by adehecq** [comment]
Thanks a lot !
