### ISSUE TITLE
virtual machine image release?

### ISSUE THREAD

**Issue by jumpjack** [NeoGeographyToolkit/StereoPipeline#374]
It would be great if you could release at least one version as a single virtualmachine imagefile which does not require installing, but just opening/launching the file in the virtual machine. This would make it much  easier to use the tool in Windows environment for non-experienced users (lime me :-) ).

**Comment by oleg-alexandrov** [comment]
ASP already can be used without installing. One just downloads the right tarball from https://github.com/NeoGeographyToolkit/StereoPipeline/releases, extracts, and runs it with /path/to/your/user/dir/asp/bin/parallel_stereo.

The conda installation of ASP is also rather straightforward, it is just a short sequence of commands, not that different than using apt-get or yum to install system things, and does not require a root password.

When it comes to installing as a virtual machine image file, there are too many virtual machine kinds out there, like VirtualBox, VMWare, etc , and a VM image would be huge as it would incorporate the whole system. I guess Docker is the way to go here, but that would require installing Docker too.

**Comment by oleg-alexandrov** [comment]
To add, on Windows you can install WSL, then extract ASP in it. I know it works, as verified by some folks who use it that way. But you'd need to get the latest version, 3.1.0, as I fixed some path issues on WSL not so long ago.
