### ISSUE TITLE
rig_utils.py missing from libexec

### ISSUE THREAD

**Issue by AndrewAnnex** [NeoGeographyToolkit/StereoPipeline#380]
**Describe the bug**
As of the daily build from 8/3/22, running theia_sfm or multi_stereo caused an modulenotfounderror for `rig_utils`. Looking at the source it looks like it is expected to be in the `libexec` folder, but it's not there and not in this github repo. Finding a copy of it from the MultiView repo and downloading it seems to solve the issue, but it should be distributed with asp.

**To Reproduce**
1. install asp from StereoPipeline-3.1.1-alpha-2022-08-03-x86_64-Linux.tar.bz2
2. add the bin dir to the path
3. run `theia_sfm` with no arguments

**Expected behavior**
Looks like the file just needs to be added to ASP, I could look into making the pr...

**Error Logs, Terminal Captures, Screenshots**
```
(base) ➜  bin ./theia_sfm
Traceback (most recent call last):
  File "/home/annex/tools/asp_3_1_1_a_8_3_22/libexec/theia_sfm", line 31, in <module>
    import rig_utils
ModuleNotFoundError: No module named 'rig_utils'
```

**Comment by oleg-alexandrov** [comment]
My bad. I added it. Should be in the latest build tomorrow. Thank you for pointing this out.

**Comment by AndrewAnnex** [comment]
@oleg-alexandrov we can close this issue right?

**Comment by oleg-alexandrov** [comment]
Indeed. If there are any other glitches, do let me know. You're the first user and my plan on further improving the new tools more have been dashed given other recent unexpected priorities, but I'll try to address quickly any problems.
