### ISSUE TITLE
Integration with spiceinit web service

### ISSUE THREAD

**Issue by Hyradus** [NeoGeographyToolkit/StereoPipeline#389]
**Is your feature request related to a problem? Please describe.**
Due to recent changes in ISISDATA structure, I cannot process anymore hiedr2mosaic.py since it crash at spice function due to missing kernels.
My ISISDATA is updated to the recent version.
Running the hiedr2mosaic.py commands one by one, highlight exactly the probelm with spiceinit since if I use spiceinit WEB=True, it works flawlessly.

**Describe the solution you'd like**
Add a new argument to hiedr2mosaic.py to enable spiceinit web

I have already edited hiedr2mosaic.py with the new argument and tested with success.
```
def spice( cub_files, threads, web):
    for cub in cub_files:
        cmd = f'spiceinit WEB={web} from={cub}'
        add_job(cmd, threads)
    wait_on_all_jobs()
    for cub in cub_files:
        cmd = 'spicefit from= '+ cub
        add_job(cmd, threads)
    wait_on_all_jobs()
    return
```

and in the main function

```
[...]
parser.set_defaults(web=False)
[...]
parser.add_option("-w", "--web", dest="web",
                              help="Uses spiceinit web (default False).")
[...]
```

I'll create a PR if this is ok.

**Describe alternatives you've considered**

**Additional context**
This may be implemented also to other scripts such as lronac2mosaic.py

**Comment by Hyradus** [comment]
@oleg-alexandrov PR already under review :)

**Comment by oleg-alexandrov** [comment]
Would be so nice if every day code would just write itself. :)

**Comment by okaragoz** [comment]
I have the same problem, after updating ISIS. I did the synchronization with `downloadIsisData mro $ISISISDATA`. 
However, I try to process CTX EDR using `mroctx2isis` but got errors about missing kernels.

`**ERROR** No existing files found with a numerical version matching [kernels.????.db] in [/isis/mro/kernels/pck].`

ISIS version is 7.1.0
ASP version 3.2.0

After synchronizing two times using `downloadIsisData mro $ISISDATA`, when I look inside my ISISDATA/mro/kernels/pck file, I can only find a kernel file _kernels.0001.db._
