### ISSUE TITLE
geodiff could be made faster

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#40]
Given two DEMs, A.tif and B.tif, the command

geodiff A.tif B.tif

can be hundreds of times slower than 

geodiff B.tif A.tif

That happens if A.tif covers a huge area but B.tif a smaller one. I think geodiff could be more clever in first finding the intersection of the bounding boxes of the two images and finding the diff only in that area.

More seriously, geodiff A.tif B.tif returned an empty result (after all that work), while the reverse returned a good result. Perhaps it is because the grids were different. 

I'll perhaps get to fixing this issue myself at some point, I put it here to make sure it is not forgotten.

**Comment by ScottMcMichael** [comment]
Done.
