### ISSUE TITLE
Problem with conda and channel 

### ISSUE THREAD

**Issue by tthomopoulos** [NeoGeographyToolkit/StereoPipeline#400]
Hi,

I try to install asp with conda, but when I run the install command, it gives me the following message.

"(base) @Mini-de-Thomas / % conda install stereo-pipeline==3.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - stereo-pipeline==3.2.0

Current channels:

  - https://conda.anaconda.org/nasa-ames-stereo-pipeline/osx-arm64
  - https://conda.anaconda.org/nasa-ames-stereo-pipeline/noarch
  - https://conda.anaconda.org/usgs-astrogeology/osx-arm64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page".

Channels are well configured :

"(base) @Mini-de-Thomas / % conda config --env --add channels conda-forge
(base) @Mini-de-Thomas / % conda config --env --add channels usgs-astrogeology
(base) @Mini-de-Thomas / % conda config --env --add channels nasa-ames-stereo-pipeline
(base) @Mini-de-Thomas / % conda config --show channels
channels:
  - nasa-ames-stereo-pipeline
  - usgs-astrogeology
  - conda-forge
  - defaults"

It seems not to find stereo pipeline on conda. 

Could you help me to install it? Thanks 

My computer is a Mac Mini M1 with Mac Os X Monterey version 12.6.5

Thomas

**Comment by oleg-alexandrov** [comment]
ASP does not support M1, only the Intel processor. I heard people ran
successfully the Intel binaries via the translation layer. Those can be
obtained from https://github.com/NeoGeographyToolkit/StereoPipeline/releases
.

**Comment by rbeyer** [comment]
Since ASP depends on the USGS's ISIS software libraries, and until those are fully functional natively on Apple Silicon, we can't do much about it.

For now, it does appear that running conda, ISIS, and ASP via the translation layer might work for some folks.  You can also certainly experiment with virtualization solutions to try and run a Linux image to install ISIS and ASP in.

Of course, as Oleg says, you should be able to run the pre-compiled ASP Intel binaries via the translation layer.  Of course, running ASP with a Mac Mini is a brave act, and we salute you.

**Comment by oleg-alexandrov** [comment]
Based on https://github.com/DOI-USGS/ISIS3#installation, they don't do have custom binaries for M1, and they trick your system into installing x86-64 and Rosetta. Can the same instructions be used with ASP?

**Comment by oleg-alexandrov** [comment]
I understand. I was wondering if one can ignore the ASP instructions and use the ISIS instructions that worked for you, except for adding the ASP channel on top of the rest. I surely understand if you find these things too tricky, and it should be on our side to sort things out. 

For now, one should not use conda then with M1, and download the ASP tarball as in https://stereopipeline.readthedocs.io/en/latest/installation.html. I know from people that that approach works.
