### ISSUE TITLE
reference to IAGD interest point detector?

### ISSUE THREAD

**Issue by steo85it** [NeoGeographyToolkit/StereoPipeline#401]
Hi! Would you have a reference for the `IAGD` interest point detector? I can't find it anywhere else beside in the `ipfind` docu section. Thanks!

**Comment by ScottMcMichael** [comment]
IAGD stands for Integral Auto Gain Detector, it looks like a variant of OBALog which is described here: https://krex.k-state.edu/handle/2097/3651

https://github.com/visionworkbench/visionworkbench/blob/master/src/vw/InterestPoint/IntegralDetector.h

**Comment by steo85it** [comment]
That's helpful, thanks Scott!

**Comment by oleg-alexandrov** [comment]
I added to the ipfind, bundle_adjust, and stereodefault doc pages a citation for OBALoG, then mentioned that IAGD is a variant of OBALoG. I could not find a reference for IAGD, it is likely something that was cooked up in-house, based the code comments.
