### ISSUE TITLE
image_ Mosaic encountered the following issues

### ISSUE THREAD

**Issue by cc863** [NeoGeographyToolkit/StereoPipeline#402]
virtual-machine:~$ image_mosaic D3C1216-200548F040_a.tif D3C1216-200548F040_b.tif D3C1216-200548F040_c.tif D3C1216-200548F040_d.tif D3C1216-200548F040_e.tif D3C1216-200548F040_f.tif D3C1216-200548F040_g.tif D3C1216-200548F040_h.tif 
D3C1216-200548F040_i.tif D3C1216-200548F040_j.tif D3C1216-200548F040_k.tif D3C1216-200548F040_l.tif --ot byte --overlap-width 3000 -o D3C1216-200548F040.tif
	--> Setting number of processing threads to: 4
Using blend radius: 3000
Matching interest points between: D3C1216-200548F040_a.tif andD3C1216-200548F040_b.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 3304
relative_transform: Matrix3x3((1,-0.000191746,28878.3)(0.000191746,1,85.7983)(0,0,1))
absolute_transform: Matrix3x3((1,-0.000191746,28878.3)(0.000191746,1,85.7983)(0,0,1))
Matching interest points between: D3C1216-200548F040_b.tif and D3C1216-200548F040_c.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 2713
relative_transform: Matrix3x3((1,8.61062e-05,29111.1)(-8.61062e-05,1,59.3715)(0,0,1))
absolute_transform: Matrix3x3((1,-0.00010564,57989.5)(0.00010564,1,150.752)(0,0,1))
Matching interest points between:D3C1216-200548F040_c.tif and D3C1216-200548F040_d.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 2258
relative_transform: Matrix3x3((1,0.000402694,29645)(-0.000402694,1,90.0609)(0,0,1))
absolute_transform: Matrix3x3((1,0.000297055,87634.4)(-0.000297055,1,243.944)(0,0,1))
Matching interest points between: D3C1216-200548F040_d.tif and D3C1216-200548F040_e.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 2558
relative_transform: Matrix3x3((1,-9.38273e-05,29116.8)(9.38273e-05,1,51.4095)(0,0,1))
absolute_transform: Matrix3x3((1,0.000203227,116751)(-0.000203227,1,286.705)(0,0,1))
Matching interest points between: D3C1216-200548F040_e.tif and D3C1216-200548F040_f.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 2706
relative_transform: Matrix3x3((1,-0.000146888,29075.3)(0.000146888,1,90.9067)(0,0,1))
absolute_transform: Matrix3x3((1,5.63391e-05,145827)(-5.63391e-05,1,371.702)(0,0,1))
Matching interest points between: D3C1216-200548F040_f.tif and D3C1216-200548F040_g.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 3230
relative_transform: Matrix3x3((1,6.19424e-05,29022.9)(-6.19424e-05,1,29.9399)(0,0,1))
absolute_transform: Matrix3x3((1,0.000118282,174850)(-0.000118282,1,400.007)(0,0,1))
Matching interest points between: D3C1216-200548F040_g.tif and D3C1216-200548F040_h.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4997
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4979
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 2395
relative_transform: Matrix3x3((1,8.60085e-05,29427.2)(-8.60085e-05,1,76.8338)(0,0,1))
absolute_transform: Matrix3x3((1,0.00020429,204277)(-0.00020429,1,473.36)(0,0,1))
Matching interest points between: D3C1216-200548F040_h.tif and D3C1216-200548F040_i.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4958
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4937
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 100%
	    Matched points: 2754
relative_transform: Matrix3x3((1,-0.000198958,28963.3)(0.000198958,1,51.0932)(0,0,1))
absolute_transform: Matrix3x3((1,5.33182e-06,233240)(-5.33182e-06,1,518.537)(0,0,1))
Matching interest points between: D3C1216-200548F040_i.tif and D3C1216-200548F040_j.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4979
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4970
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 99%
	    Matched points: 2106
relative_transform: Matrix3x3((1,-0.000267988,28783)(0.000267988,1,88.9589)(0,0,1))
absolute_transform: Matrix3x3((1,-0.000262656,262023)(0.000262656,1,607.342)(0,0,1))
Matching interest points between: D3C1216-200548F040_j.tif and D3C1216-200548F040_k.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4957
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4979
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 100%
	    Matched points: 2682
relative_transform: Matrix3x3((1,6.42377e-05,28958.8)(-6.42377e-05,1,30.1705)(0,0,1))
absolute_transform: Matrix3x3((1,-0.000198419,290982)(0.000198419,1,645.119)(0,0,1))
Matching interest points between: D3C1216-200548F040_k.tif and D3C1216-200548F040_l.tif
	    Looking for IP in left image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4965
	    Looking for IP in right image...
	    Using 71 interest points per tile (1024^2 px).
	    Detecting IP
	    Building descriptors
	    Found interest points: 4954
	--> Uniqueness threshold: 0.8
           Matching: [***************************************************.] 100%
	    Matched points: 2275
relative_transform: Matrix3x3((1,0.000176411,29399.3)(-0.000176411,1,77.9228)(0,0,1))
absolute_transform: Matrix3x3((1,-2.20076e-05,320381)(2.20076e-05,1,728.875)(0,0,1))
Writing: D3C1216-200548F040.tif
Using temporary block size: 6000
            Mosaic:[......................................................] 0%Killed

**Comment by oleg-alexandrov** [comment]
Maybe it was using a lot of memory and your system killed it? You can try running "top" in another terminal to keep watch on it. You can also try to maybe not mosaic them at the same time, but in several steps (mosaic 2nd to first, then 3rd to union of first two). Or you can try working at a lower resolution first (using gdal_translate -r average).
