### ISSUE TITLE
cropping cameras for bundle_adjust

### ISSUE THREAD

**Issue by steo85it** [NeoGeographyToolkit/StereoPipeline#407]
Hi! I am running `parallel_bundle_adjust` on a set of LROC-NAC cameras (.cub + csm .json) along with their map-projected version on a limited target region of 1x1 km. Now, loading the (~200) cameras takes a (comparatively) long time, especially for the statistics and matching step, just because they still cover their original field of view instead of pixels covering the "target region", only. 

Would it be possible to "crop" the input camera files to the target region, too, and if yes, how to proceed when knowing the max/min lon/lat of the target region? (for this specific case, matches are computed within that limited region between map-projected images, anyway)
Thanks!

**Comment by oleg-alexandrov** [comment]
When interest points are created using the --mapprojected-data option, they
are only made within the areas seen in the mapprojected images. So, you can
try cropping the mapprojected images and restart bundle adjustment (after
wiping all existing matches). I believe the statistics are also done on the
mapprojected images, if you have them.

If you already have a lot of matches, but want to keep only those in your
area of interest (which is not your goal, but is a related thing), one can
use the option: --proj-win in bundle_adjust (
https://stereopipeline.readthedocs.io/en/latest/tools/bundle_adjust.html).

Let me know if this does not address the issue.

**Comment by steo85it** [comment]
Trying now, thanks! However, I do not have matches, yet (so I am running through all "3 steps" of BA - not sure if that changes your take on the issue).
(also, for disclosure, what I have are output and log files from a previous - much faster - run by "colleagues" that I am trying to "reverse-engineer" with the same set of images/cameras and target region)

**Comment by oleg-alexandrov** [comment]
OK, you can see how it goes. My best guesses (and please correct them) are:
(a) json files load fast, and a repeated run can verify that (b) statistics
and interest point matching happen only once and only for cropped
mapprojected data so time is proportional to mapprojected image extent.

**Comment by steo85it** [comment]
I am starting to think that the main "issue" here is with `parallel_bundle_adjust` loading all cameras for each instance (input image) to produce statistics for a single image. When a lot of images are provided (>> # of available cores), that's probably not necessarily worth the "distribution" (the test you suggested is taking, if I extrapolate, ~1h to load the cameras - ~25"/camera - and probably 5 min or less to generate statistics for all images). 

I am also still unsure how the "example" that I am reverse-engineering got to use such smaller camera files to bundle-adjust the same NAC images...

> To answer your question though, functionality for cropping CSM cameras does
not exist.

Have they maybe cropped the ISIS cameras before converting them (although I thought that was also not possible, yet)

**Comment by oleg-alexandrov** [comment]
>
> I am starting to think that the main "issue" here is with
> parallel_bundle_adjust loading all cameras for each instance (input
> image) to produce statistics for a single image. When a lot of images are
> provided (>> # of available cores), that's probably not necessarily worth
> the "distribution" (the test you suggested is taking, if I extrapolate, ~1h
> to load the cameras - ~25"/camera - and probably 5 min or less to generate
> statistics for all images).
>
This is likely. We did not optimize for that as it did not appear that
loading a few hundred cameras at the same time would be a problem, even if
multiple processes do that at the same time. It would be quite some work to
optimize this, as the camera loading happens in a different part of the
code and it does not know yet about what cameras will be needed later.

You can still run a single instance of bundle_adjust after all stats and
matches are done, and see just how long it takes to simply load 200
cameras. Then, maybe one can use a smaller value for --processes, since
each process uses multiple threads when finding interest point matches,
which takes longer than fiding stats.

Anyhow, I will keep this in mind when I revisit large-scale
bundle_adjustment with many .json files. I never found this to be a
bottleneck, in the grand scheme of things, but that's because maybe such a
work takes tens of hours usually and gets done overnight.

**Comment by steo85it** [comment]
Yes, I confirm my estimates above (1h for loading, 5 min for the stats). I will manually set a single `bundle_adjust` with `--stop-after-statistics`  (1h << 15h :) ), then run `parallel_bundle_adjust` from there to distribute matches computations. 
That should solve this issue for these experiments, and I will later ask how did they get to work with those smaller cameras, as it can still be helpful in other instances. Thanks for the feedback!

**Comment by steo85it** [comment]
We finally figured out that I had been using the `gen_csm.py` script from the manual meant for frame cameras ([8.13.1.2](https://stereopipeline.readthedocs.io/en/latest/examples/csm.html#create-csm-dawn) ) instead of the one for line cameras ([8.13.2.1](https://stereopipeline.readthedocs.io/en/latest/examples/csm.html#create-csm-linescan)). That changes the size of the output .json from ~150KB to ~25MB in the case of an LROC NAC image (hence my "nonsense question").

Clearly my mistake of not reading carefully, but I would suggest:
- extending the subsection title to make them clearer;
- updating the suggested script names to, e.g., `gen_csm_frame.py`, `gen_csm_line.py`, `gen_csm_sar.py` to help the "distracted" user; 
- add a warning about possible consequences (e.g., "using 8.13.1.2 on linescan cameras will still work, but it will result in cameras 100+ times larger, and much longer loading/processing times").

Thanks!

**Comment by rbeyer** [comment]
What we should really do is double-check that this functionality is reproduced by the isd_generate program distributed in the ALE distribution, and then switch the documentation to have users just operate that program appropriately.

**Comment by oleg-alexandrov** [comment]
Yes, we need to test that every single example with the doc can work with the isd_generate program, and ensure that this tool can handle all CSM sensors. 

For now I implemented Stefano's suggestions 1 and 2. I did not put the warning as that would need to go in every single section, and hoping clearer names should be enough. Also, the user would notice they do the wrong thing as soon as they do something useful with the data, like stereo or mapproject, as then the results would be total junk if a different sensor class is used.

**Comment by steo85it** [comment]
Thanks for the prompt update! And ok, I was not aware of that upcoming development.

> Also, the user would notice they do the wrong thing as soon as they do something useful with the data, like stereo or mapproject, as then the results would be total junk if a different sensor class is used.

I am not sure about this, though: I was indeed using the "wrong thing" (`gen_csm_frame.py` for LROC NAC) but my mapprojected images looked ok, as well as `sfs` simulated images and `bundle_adjust` results. (not to say that one should absolutely add that warning, but just to point out this specific case)
