### ISSUE TITLE
stereo_gui not working with port forwarding

### ISSUE THREAD

**Issue by ShashankBice** [NeoGeographyToolkit/StereoPipeline#410]
**Describe the bug**
Latest version of stereo_gui does not work on remote x11 forwarding setup, old version from 2022 does.

**To Reproduce**
1. Run stereo_gui as: `stereo_gui img.tif --delete-temporary-files` on pfe, with ssh from a local linux machine using `ssh -Y pfe`
2. Program starts, builds overviews (*sub_x.tif files), but fails at display step saying the x11 connection broke, full error log pasted below. I am not very familiar with the software involved behind the scenes, so pardon me for the limited info I am able to provide. 

**Expected behavior**
The images would have loaded up on my local machine

**Error Logs, Terminal Captures, Screenshots**
```--> Setting number of processing threads to: 4
Reading: img.tif
Detected large image: img.tif. Will construct an image pyramid on disk.
Using existing subsampled image:img_sub2.tif
Using existing subsampled image: img_sub4.tif
Using existing subsampled image: img_sub8.tif
Using existing subsampled image: img_sub16.tif
Using existing subsampled image: img_sub32.tif
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:25.0"
      after 333 requests (333 known processed) with 0 events remaining.
```

**Your Environment (please complete the following information):**
 - OS: [Remote OS: Pleiades, 4.18.0-477.21.1.1toss.t4.x86_64, Local OS: Ubuntu VERSION="20.04.4 LTS (Focal Fossa)" 
 - ASP Version: [3.4.0-alpha, build date: 2023-08-23]. It works on ASP version [3.0.0, build date: 2022-01-26]  

Please let me know how to proceed,
Thanks,
Shashank

**Comment by oleg-alexandrov** [comment]
I tried connecting to Pleiades with ssh -Y and it worked. I got a gui
window. My own build is 3.4.0-alpha-2023-09-17, but I don't think it
matters.

Are you able to start any other gui program, such as xterm? This is an
error in setting up an X connection and should apply to any GUI programs.

See if things work with ssh -Y to pfe26. I did not try other nodes.

I usually use vncserver on Pleiades, as then the gui loads faster, but I
heard they are going to deprecate this.

**Comment by ShashankBice** [comment]
Hi Oleg,
Thanks for the guidance, latest version works using a vnc setup!

**Comment by steo85it** [comment]
I actually have the same issue... ASP 3.2.1 would open stereo_gui w/o issues, while in the same session 3.4.0 (and 3.3.0, too) would throw
```
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:13.0"
      after 344 requests (344 known processed) with 0 events remaining.
```
This is my only reason to keep ASP 3.2.1 as my default version for "interactive sessions".

**Comment by oleg-alexandrov** [comment]
I don't think I did anything different this time than updating the libraries as needed by the dependencies.

Since you have both versions, you could try to see what you get for each when it comes to libX* and libGL*, and libQt*.

I also found this: https://kowalcj0.github.io/2018/02/11/vlc-auto-screen-scale-factor-issue/
And this: https://github.com/gnuradio/gnuradio/issues/3568

For me it works to pop up stereo_gui over ssh.  I have Ubuntu 18.04.6 on the remote machine, and Mint 21.3 locally. Also works with Ubuntu 20.04.6 locally. 

So, I can't reproduce this on my side. I suspect there's some mismatch between X versions or libraries on those machines.

**Comment by oleg-alexandrov** [comment]
To add to previous, starting a vnc session on the remote machine should work. Then locally you just transfer pixels and don't need to worry about library compatibility (it is also faster this way, I think).
