### ISSUE TITLE
VW Error: RANSAC was unable to find a fit that matched the supplied data.

### ISSUE THREAD

**Issue by cyclonebluse** [NeoGeographyToolkit/StereoPipeline#415]
**Describe the bug**
When I use HRSC image to run parallel_stereo ,I get the error:VW Error: RANSAC was unable to find a fit that matched the supplied data.Of course, I refer to the error of Pippo-90https://github.com/NeoGeographyToolkit/StereoPipeline/issues/395, I then tested all the relevant HRSC images for that area but failed,and using images from other areas yielded the correct results.
**To Reproduce**
stereo_gui HD674_0000_S12.cub HD674_0000_S22.cub --left-image-crop-win 19 12646 2540 1981 --right-image-crop-win 2 13040 2567 1944 --stereo-algorithm asp_sgm --subpixel-mode 3 run/run

**Expected behavior**
I want to use HRSC images to get topographic information and DEM about the area of interest

**Error Logs, Terminal Captures, Screenshots**
<img width="364" alt="image" src="https://github.com/NeoGeographyToolkit/StereoPipeline/assets/102231911/0ad75163-6ab3-445d-ba60-8e97d983c28e">

**Your Environment (please complete the following information):**
 - OS: [ Linux Ubuntu 22.04.2]
 - ASP Version: [3.2.1-alpha]

**Additional context**
It's also possible that the terrain in this area is too flat and lacks features, but I set ’--corr-seed-mode 0 --corr-max-levels 2‘and it does't work,The topography of the area is roughly as follows.
![HD674_0000_S12](https://github.com/NeoGeographyToolkit/StereoPipeline/assets/102231911/f5961b8d-6ec6-493a-ab92-4ac85c8b31a0)

**Comment by oleg-alexandrov** [comment]
When you run:

stereo_gui HD674_0000_S12.cub HD674_0000_S22.cub --left-image-crop-win 19 12646 2540 1981 --right-image-crop-win 2 13040 2567 1944 --stereo-algorithm asp_sgm --subpixel-mode 3 run/run

you should see two red rectangles having the areas of interest. Can you share a picture of that screenshot? 

My best guess is that the left and right image are not similar enough in those selected areas.

**Comment by cyclonebluse** [comment]
Thank you for answering my question. It seems to me that the similarity of the selected area is good,Whether use the entire image or crop the image, the same error will be reported.I feel like this doesn't seem to be due to cutting.
<img width="596" alt="image" src="https://github.com/NeoGeographyToolkit/StereoPipeline/assets/102231911/014fa144-6c11-4704-aea4-153e6a067a4f">

**Comment by oleg-alexandrov** [comment]
Good to see the actual area. You can try wiping the entire run directory and rerun with --ip-per-tile 4000. That can be slow but will try to create more matches.

If still no luck, and you can share your two .cub images (on Google drive or something), I can try to reproduce this. (I know the dataset is public but it takes time to get the data, kernels, preprocess it, etc.)

**Comment by cyclonebluse** [comment]
It's a pity that I've been running for a long time and I'm not getting results，I'll upload the image later

**Comment by cyclonebluse** [comment]
[Uploading part1.zip…]()
[Uploading part2.zip…]()

**Comment by cyclonebluse** [comment]
[Uploading part1.zip…]()
[Uploading part2.zip…]()

**Comment by cyclonebluse** [comment]
Ok, thanks for testing, I can probably see why the error occurred.But I tried the other images in the area (there are only two tracks in this area, D674 and D755), and unfortunately the same error occurred when I ran it, but if I chose a different area, it worked fine.But the strange thing is that the Level 3 data provided by the USGS was made with the D755 track.

**Comment by cyclonebluse** [comment]
Then I wondered if there was another way to match the type of imagery

**Comment by oleg-alexandrov** [comment]
I added matches manually, following https://stereopipeline.readthedocs.io/en/latest/tools/stereo_gui.html#edit-interest-point-matches. I had to add around 20 matches or else the tool will complain. Here's an illustration:
<img width="416" alt="image" src="https://github.com/NeoGeographyToolkit/StereoPipeline/assets/1325676/c52f313e-2937-430a-927f-2c9fcf80804a">

Then I saved them, as run/run-HD755_0000_S12__HD755_0000_S22.match. The file is attached below:
[run-HD755_0000_S12__HD755_0000_S22.match.zip](https://github.com/NeoGeographyToolkit/StereoPipeline/files/13452608/run-HD755_0000_S12__HD755_0000_S22.match.zip)

Then, quit the gui and run:

stereo --min-num-ip 1 --stereo-algorithm asp_bm --subpixel-mode 1 --skip-rough-homography --max-disp-spread 200 --corr-seed-mode 1 --threads 16 HD755_0000_S12.cub HD755_0000_S22.cub --global-alignment-threshold 1000 run/run

This is working so far, I got: 
<code>
Convergence angle percentiles (in degrees) based on interest point matches:
    25% 43.4012, 50% 43.747, 75% 44.4924.
D_sub search range: (Origin: (-17.125, -7.75) width: 31.25 height: 17.5) px
    --> Full-res search range based on D_sub: (Origin: (-93, -50) width: 186 height: 107)
Writing: run/run-D.tif
        --> Correlation :[**********......................................] 22%
</code>

The search range is a little big but reasonable. 

I used here the asp_bm algorithm, but asp_mgm with parallel_stereo should work as well.

**Comment by cyclonebluse** [comment]
Thanks for the help and suggestion, next I'll try to add the match points manually and then run stereo, hopefully this will work for that area.

**Comment by cyclonebluse** [comment]
I tried the methods mentioned above, but the DEM results I get seem to be discrete and incomplete.I tried to pick the matching points myself and used parallel_stereo with the asp_mgm algorithm, which ran for a long time but the results didn't seem to be good.When I used stereo, the process of Correlation was lengthy, and at one point it even returned Correlation Failed.Perhaps this is a viable approach, but more experimentation is needed.

**Comment by oleg-alexandrov** [comment]
The problem is, as before, that the lightning is too different in the two images. I don't know how the other good DEMs for that area were obtained. 

You can try to see if there's other HRSC datasets, or even CTX datasets.

**Comment by cyclonebluse** [comment]
Thank you for your help and advice,Unfortunately, after two days of hard work, I used HiRise imagery this time, but the results in this area were still not satisfactory.This is very strange, the terrain in this area is too smooth and lacks large-scale features, so that it runs for a very long time and the Good-pixel Map looks very discrete,This question does confuse me, but thank you again for your help and for giving me some ideas and solutions to the problem that may be useful in other situations.
