### ISSUE TITLE
Issue Encountered During DEM Generation with ASP and Request for Assistance

### ISSUE THREAD

**Issue by silverbean-j** [NeoGeographyToolkit/StereoPipeline#419]
Hello team,

I'm currently working on generating a DEM using ASP. However, I've encountered an issue. The "-PC_sub.tif" output was generated successfully, but the "-PC.tif" output wasn't created, and an error message occurred. Previously, during testing, I used the version `StereoPipeline-3.4.0-alpha-2023-09-17-x86_64-Linux`, but now I'm encountering this problem using the `StereoPipeline-3.3.0-Linux version`. I'm running ASP within a Docker container using an Ubuntu image.

I formulated the command following Chapter 5.2 "Processing raw" in your tutorial:
```
docker exec -it asp /StereoPipeline-3.3.0-Linux/bin/parallel_stereo -t rpc --stereo-algorithm asp_mgm --subpixel-mode 9 --alignment-method affineepipolar /data/test/ref_img.tif /data/test/ref_img.xml /data/test/tar_img.tif /data/test/tar_img.xml /data/test/tmp_output
```

The imagery I'm working with is similar to WorldView, and I aim to generate both Panchromatic and Multi-Spectral images. Could you please verify if the command I'm using is incorrect or flawed? I'd appreciate it.

Additionally, if you require the images and RPC files I'm using, could you provide an email address where I can send them?

Unfortunately, even using | tee stereo_output.log, the log file isn't generated, so I'll attach the contents displayed in the command prompt.
[ASP_log.txt](https://github.com/NeoGeographyToolkit/StereoPipeline/files/13595239/ASP_log.txt)

I would be truly grateful for your assistance. Thank you.

**Comment by oleg-alexandrov** [comment]
The order of inputs should be as follows: first images, then cameras, so: 

/data/test/ref_img.tif /data/test/tar_img.tif  /data/test/ref_img.xml  /data/test/tar_img.xml

followed by output prefix.

Somehow, however, in your case the workflow continues. Then it runs into large disparity issues:

   Refined search range using a histogram and --outlier-removal-params: (Origin: (-8285, -573) width: 14754 height: 1031)

That is bad.

I will suggested using the mapprojected images workflow: https://stereopipeline.readthedocs.io/en/latest/next_steps.html#mapproj-example

One should ensure dem_geoid gets used as stated there to correct any input DEM if applicable, then one should mapproject left and right image at same resolution as suggested further down. It is strongly suggested to examine the two produced images. They should be very similar if overlaid. And note that the invocation of parallel_stereo will be different, as shown in that example, with a DEM at the end.

**Comment by silverbean-j** [comment]
Hello,

Thank you for providing a response in the first place. I'm trying to follow the solution you provided, but it seems like either I'm not understanding it properly or I might have conveyed something incorrectly.

Firstly, according to that document, it seems I should have a DEM for the respective imagery. However, I don't have the DEM for that imagery (hence, it needs to be generated). Previously, the command I provided actually resulted in the imagery being successfully produced (I'll attach the DEM that I actually generated additionally). However, currently, it's not working.

[ASP_Crop_log.txt](https://github.com/NeoGeographyToolkit/StereoPipeline/files/13630855/ASP_Crop_log.txt)

I even tried cutting the imagery as per the instructions in the document, but it still isn't working. I'm not sure if the disparity values are still causing an issue.

Could it be that I'm misunderstanding something? Also, just to note, I don't have the .cub file.

Thank you so much for your assistance!

![ASP_MS_Result_with_QTReader](https://github.com/NeoGeographyToolkit/StereoPipeline/assets/97012621/8d71133e-bfe6-4c6b-86f1-3c55b990ce0c)
![ASP_MS_Result_with_QGIS](https://github.com/NeoGeographyToolkit/StereoPipeline/assets/97012621/3ad58f2b-e257-4b34-a215-2c190531ca11)

**Comment by oleg-alexandrov** [comment]
You need .cub files only for outer planets, not for Earth.  See if the
documentation at
https://stereopipeline.readthedocs.io/en/latest/examples.html can help you
get started. Choose the right section for your data. Maybe you have RPC
data.

Normally with ASP you don't need an initial DEM if you have good left and
right images that are quite similar, have good convergence angle and good
features (
https://stereopipeline.readthedocs.io/en/latest/examples/stereo_pairs.html),

A DEM is needed only when the disparity range is too large, but that
assumes you already have a good dataset.

As to where to get initial DEM, if you need them, that is discussed at
https://stereopipeline.readthedocs.io/en/latest/next_steps.html#mapproj-example
and further down.

I suggest you read these documentation pages, and practice some more.

Check your left and right input images. They should be similar. You can
also try running clips, using stereo_gui (
https://stereopipeline.readthedocs.io/en/latest/tools/stereo_gui.html).

Check for the convergence angle printed on screen.

If still no luck, you can share the precise command you used, and maybe a
screenshot from stereo_gui showing left and right images, and the stereo
convergence angle as printed on screen.
