### ISSUE TITLE
The python wrapper around GNU parallel is causing weird behaviors

### ISSUE THREAD

**Issue by otherorb** [NeoGeographyToolkit/StereoPipeline#426]
**Describe the bug**

I have freshly installed ASP from 2024-02-16 daily build. 
The parallel wrapper included with ASP is introducing some weird behavior.

% ../StereoPipeline-3.4.0-alpha-2024-02-16-x86_64-Linux/bin/parallel -S  styx0 echo ::: 1
parallel: Warning: ssh to styx0 only allows for 0 simultaneous logins.
parallel: Warning: You may raise this by changing
parallel: Warning: /etc/ssh/sshd_config:MaxStartups and MaxSessions on styx0.
parallel: Warning: You can also try --sshdelay 0.1
parallel: Warning: Using only -1 connections to avoid race conditions.
parallel: Error: Cannot run any jobs.

If I run with the GNU parallel installed on the system, I get the expected behvaior.
% /usr/bin/parallel -S sytx0 echo ::: 1
1

Similarly, if I run with an ASP version from late last year, I get the expected behavior:
% ../StereoPipeline-3.4.0-alpha-2023-10-31-x86_64-Linux/bin/parallel -S  styx0 echo ::: 1
1

**Comment by oleg-alexandrov** [comment]
I cannot reproduce this. I replaced your machine with localhost. Here's what I get:

StereoPipeline-x86_64-Linux-2024-02-16_23-16-10adca760/bin/parallel -S localhost echo ::: 1

parallel: Warning: Could not figure out number of cpus on localhost (). Using 1.
1

Can you run parallel --version? I get: 

GNU parallel 20231122

Something may be off when it comes to your own machine. Your log says: " ssh to styx0 only allows for 0 simultaneous logins."

**Comment by otherorb** [comment]
I have an older version of parallel on my system install:

/usr/bin/parallel --version
GNU parallel 20210822

May be a change in gnu parallel configuration expectations between 2021 and 2023? 
I don't know.
I'll have to suss that out later.
