### ISSUE TITLE
New paper using ASP

### ISSUE THREAD

**Issue by abhinavjindal93** [NeoGeographyToolkit/StereoPipeline#428]
**DOI**
If the work has a DOI, that's really all we need.  Please enter it.
https://doi.org/10.1029/2023JE008089

**Citation**
Otherwise, please provide as complete a citation as possible.

If you have a citation in BibTeX format, please paste that in (but it isn't required).

**Comment by oleg-alexandrov** [comment]
I added the paper to our list. That's a very nice work on using SfS, taking into account the shadows, need for a good reflectance model and diverse illumination.

This is nice " It is important to note that the errors from ASP's error estimation tool (Method 1) provide an optimistic estimate of the uncertainty in the measurement of the change in elevation when compared to Method 2.". I guess too much optimism is not a good thing. :)
