### ISSUE TITLE
Crop image and save modified RPCs

### ISSUE THREAD

**Issue by druidance** [NeoGeographyToolkit/StereoPipeline#434]
**Is your feature request related to a problem? Please describe.**
Before creating and deploying a pipeline to the PROD, I need to assess intermediate stages on smaller patches of images (I have limited infrastructure capabilities for this purpose). To refine the assessment process, I want to:
1. cut out small patches out of images with adapted RPCs
2. perform `bundle_adjust`
3. `mapproject` the resulting images
4. run `parallel_stereo` 

While `mapproject` already works with `projwin` option, it creates orthorectified images which I can't use in my assessment process.

**Describe the solution you'd like**
A command-line tool that allows to crop image while saving modified RPCs in a separate file. Something like:
`crop -t rpc image.tif ~/output/`

Once the process is finished, `~/output/` contains two files:
- image_cropped.tif
- image_cropped.rpc

**Describe alternatives you've considered**
Unfortunately, I didn't find any other solutions to my problem.

**Additional context**
Thank you for such a powerful tool :bow:. When I first found it, I couldn't believe my eyes it has so many cool features :star:.

**Comment by oleg-alexandrov** [comment]
I think the tool cam2rpc should already be doing this. https://stereopipeline.readthedocs.io/en/latest/tools/cam2rpc.html 

See if it works for you.

**Comment by oleg-alexandrov** [comment]
The height range is something you can figure approximately. It roughly
correlates with the height above sea level. If you are not sure, use 0 to
4000 or so.

The image that comes out has to be produced via a crop, so it cannot be in
any other shape than a box with sides parallel to the original sides.

These are usually not a limitation. Having both the image and range of
elevations be a little more than desired does not prevent one from testing
small areas. You just get more than what you bargained for. :)
