### ISSUE TITLE
Control verbosity level of stdout

### ISSUE THREAD

**Issue by druidance** [NeoGeographyToolkit/StereoPipeline#435]
**Is your feature request related to a problem? Please describe.**
Firstly, let's assume the output of `parallel_stereo` is redirected to a file. Then, if  `parallel_stereo` is left running for hours or even days, one gets a huge log file sizing a few GB. Analyzing such a huge file is time consuming and tedious. 

**Describe the solution you'd like**
Add a command-line flag that will control verbosity. For example:
`-v` will output only general messages (stages running, warnings?)
`-vv` will provide details (+ info about sub-stages)
`-vvv` will provide full details (+ progress bars per each sub-stage as it is right now)

**Describe alternatives you've considered**
It seems it's either suppress all the output or have it all.

**Comment by oleg-alexandrov** [comment]
A command line option would be nice. For now we have a config file option that seems to go all the way to level 0, which means no messages. https://stereopipeline.readthedocs.io/en/latest/installation.html#settings-optimization

Did you get a few GB of log though? Is it possible to tell which the worst offenders were?

**Comment by oleg-alexandrov** [comment]
You can see if this works for you:

# Turn off all progress bars to the console (not recommended).# 0 = *.progress


That is from:
https://stereopipeline.readthedocs.io/en/latest/installation.html#settings-optimization

I put it on my to-do list to have a verbosity switch, but I don't know
when I will get to it.
