### ISSUE TITLE
`bundle_adjust` failing with "image coordinate out of bounds"

### ISSUE THREAD

**Issue by steo85it** [NeoGeographyToolkit/StereoPipeline#439]
**Describe the bug**
While processing a set of MESSENGER's MDIS NAC images, I get this error when bundle-adjusting them (step 2):
```
Loaded 93042 matches.
Building the control network took 0.339873 seconds.
Triangulating: [************************..................................] 43%

Error: Image Coordinate out of Bounds
```
The error does not seem related to specific "problematic" images, and it happens on different images at different iterations of `bundle_adjust`. For the moment I managed to identify groups of images to exclude by testing all possible pairs before running bundle_adjust's optimization on the whole set of matches, but it is not very efficient/convenient.

What does this error message mean, and what is a possible cause/solution? Sorry for not providing already a minimal (non-)working example, I am working on one and this answer might help. Thanks!

**Your Environment (please complete the following information):**
 - OS: Linux
 - ASP Version: 3.3.0

**Comment by oleg-alexandrov** [comment]
I never saw this before. Do you have a reproducible example? (Hopefully a
smallish one.)

The error seems to come from ISIS. It is given a pixel it does not like.
That is unusual.

Maybe there is a mix up between image and camera order, so a pixel from a
large image is passed to a camera which expects a smaller range of pixels.

**Comment by steo85it** [comment]
Thanks! You made me think that the issue might be related to the use of CSM cameras for MDIS, and indeed I don't get this error when working with ISIS cameras on the same minimal examples... I'm testing more to see clearer into this, as I'm still getting inconsistent results.

**Comment by oleg-alexandrov** [comment]
You can check the image dimensions as recorded in a CSM camera file and the
actual image dimensions of the .cub. Anad as before the order of them.
Likely the problem is also reproducible with cam_test, if passed in a
single image and a single camera file.
