### ISSUE TITLE
unrecognised option '--streographic' when running point2dem

### ISSUE THREAD

**Issue by skyrockets-21** [NeoGeographyToolkit/StereoPipeline#440]
**Describe the bug**
unrecognised option '--streographic' when running point2dem using command as stated in
 https://stereopipeline.readthedocs.io/en/stable/examples/lronac.html#running-stereo

**To Reproduce**
After completing parallel_stereo, I run the following command:

point2dem --streographic --auto-proj-center \
  --errorimage --orthoimage                 \
    run/run-PC.tif run/run-L.tif

**Expected behavior**
Complete with no error

**Error Logs, Terminal Captures, Screenshots**
ERROR: Error parsing input:
unrecognised option '--streographic'
Usage: /home/ec2-user/SageMaker/ames_stereo_pipeline/StereoPipeline-3.5.0-alpha-2024-07-24-x86_64-Linux/libexec/point2dem [options] <point-clouds> [ --orthoimage <textures> ]

  [ASP 3.5.0-alpha]
  Build date: 2024-07-24

General options:
  --nodata-value arg (=-3.40282347e+38) Set the nodata value.
  --use-alpha                           Create images that have an alpha 
                                        channel.
  -n [ --normalized ]                   Also write a normalized version of the 
                                        DEM (for debugging).
  --orthoimage                          Write an orthoimage based on the 
                                        texture files passed in as inputs 
                                        (after the point clouds).
  -o [ --output-prefix ] arg            Specify the output prefix.
  -t [ --output-filetype ] arg (=tif)   Specify the output file.
  --errorimage                          Write an additional image, whose values
                                        represent the triangulation ray 
                                        intersection error in meters (the 
                                        closest distance between the rays 
                                        emanating from the two cameras 
                                        corresponding to the same point on the 
                                        ground). Filename is <output 
                                        prefix>-IntersectionErr.tif. If stereo 
                                        triangulation was done with the option 
                                        --compute-error-vector, this 
                                        intersection error will instead have 3 
                                        bands, corresponding to the coordinates
                                        of that vector, unless the option 
                                        --scalar-error is set.
  --scalar-error                        If the point cloud has a vector 
                                        triangulation error, ensure that the 
                                        intersection error produced by this 
                                        program is the rasterized norm of that 
                                        vector. See also --error-image.
  --dem-hole-fill-len arg (=0)          Maximum dimensions of a hole in the 
                                        output DEM to fill in, in pixels.
  --orthoimage-hole-fill-len arg (=0)   Maximum dimensions of a hole in the 
                                        output orthoimage to fill in, in 
                                        pixels.
  --orthoimage-hole-fill-extra-len arg (=0)
                                        This value, in pixels, will make 
                                        orthoimage hole filling more aggressive
                                        by first extrapolating the point cloud.
                                        A small value is suggested to avoid 
                                        artifacts. Hole-filling also works 
                                        better when less strict with outlier 
                                        removal, such as in --remove-outliers-p
                                        arams, etc.
  --remove-outliers                     Turn on outlier removal based on 
                                        percentage of triangulation error. 
                                        Obsolete, as this is the default.
  --remove-outliers-params arg (=pct factor)
                                        Outlier removal based on percentage. 
                                        Points with triangulation error larger 
                                        than pct-th percentile times factor and
                                        points too far from the cluster of most
                                        points will be removed as outliers. 
                                        [default: pct=75.0, factor=3.0]
  --use-tukey-outlier-removal           Remove outliers above Q3 + 1.5*(Q3 - 
                                        Q1). Takes precedence over 
                                        --remove-outlier-params.
  --max-valid-triangulation-error arg (=0)
                                        Outlier removal based on threshold. If 
                                        positive, points with triangulation 
                                        error larger than this will be removed 
                                        from the cloud. Measured in meters. 
                                        This option takes precedence over 
                                        --remove-outliers-params and 
                                        --use-tukey-outlier-removal.
  --max-output-size arg (=Vector2(9999999,9999999))
                                        Don't write the output DEM if it is 
                                        calculated to be this size or greater.
  --median-filter-params arg (=window_size threshold)
                                        If the point cloud height at the 
                                        current point differs by more than the 
                                        given threshold from the median of 
                                        heights in the window of given size 
                                        centered at the point, remove it as an 
                                        outlier. Use for example 11 and 40.0.
  --erode-length arg (=0)               Erode input point clouds by this many 
                                        pixels at boundary (after outliers are 
                                        removed, but before filling in holes).
  --csv-format arg                      Specify the format of input CSV files 
                                        as a list of entries 
                                        column_index:column_type (indices start
                                        from 1). Examples: '1:x 2:y 3:z', 
                                        '2:file 5:lon 6:lat 7:radius_m', '3:lat
                                        2:lon 1:height_above_datum 5:file', 
                                        '1:easting 2:northing 
                                        3:height_above_datum' (need to set 
                                        --csv-proj4). Can also use radius_km 
                                        for column_type.
  --csv-proj4 arg                       The PROJ.4 string to use to interpret 
                                        the entries in input CSV files, if 
                                        those files contain Easting and 
                                        Northing fields. If not specified, 
                                        --t_srs will be used.
  --filter arg (=weighted_average)      The filter to apply to the heights of 
                                        the cloud points within a given 
                                        circular neighborhood when gridding 
                                        (its radius is controlled via 
                                        --search-radius-factor). Options: 
                                        weighted_average (default), min, max, 
                                        mean, median, stddev, count (number of 
                                        points), nmad (= 1.4826 * median(abs(X 
                                        - median(X)))), n-pct (where n is a 
                                        real value between 0 and 100, for 
                                        example, 80-pct, meaning, 80th 
                                        percentile). Except for the default, 
                                        the name of the filter will be added to
                                        the obtained DEM file name, e.g., 
                                        output-min-DEM.tif.
  --rounding-error arg (=0.0009765625)  How much to round the output DEM and 
                                        errors, in meters (more rounding means 
                                        less precision but potentially smaller 
                                        size on disk). The inverse of a power 
                                        of 2 is suggested. Default: 1/2^10.
  --search-radius-factor arg (=0)       Multiply this factor by dem-spacing to 
                                        get the search radius. The DEM height 
                                        at a given grid point is obtained as a 
                                        weighted average of heights of all 
                                        points in the cloud within search 
                                        radius of the grid point, with the 
                                        weights given by a Gaussian. Default 
                                        search radius: max(dem-spacing, 
                                        default_dem_spacing), so the default 
                                        factor is about 1.
  --propagate-errors                    Write files with names 
                                        {output-prefix}-HorizontalStdDev.tif 
                                        and {output-prefix}-VerticalStdDev.tif 
                                        having the gridded stddev produced from
                                        bands 5 and 6 of the input point cloud,
                                        if this cloud was created with the 
                                        option --propagate-errors. The same 
                                        gridding algorithm is used as for 
                                        creating the DEM.
  --gaussian-sigma-factor arg (=0)      The value s to be used in the Gaussian 
                                        exp(-s*(x/grid_size)^2) when computing 
                                        the DEM. The default is -log(0.25) = 
                                        1.3863. A smaller value will result in 
                                        a smoother terrain.
  --default-grid-size-multiplier arg (=1)
                                        If the output DEM grid size 
                                        (--dem-spacing) is not specified, 
                                        compute it automatically (as the mean 
                                        ground sample distance), and then 
                                        multiply it by this number. It is 
                                        suggested that this number be set to 4 
                                        though the default is 1.
  --use-surface-sampling                Use the older algorithm, interpret the 
                                        point cloud as a surface made up of 
                                        triangles and interpolate into it 
                                        (prone to aliasing).
  --fsaa arg (=1)                       Oversampling amount to perform 
                                        antialiasing (obsolete).
  --no-dem                              Skip writing a DEM.
  --input-is-projected                  Input data is already in projected 
                                        coordinates, or is a point cloud in 
                                        Cartesian coordinates that is small in 
                                        extent. See the doc for more info.

Manipulation options:
  --x-offset arg (=0)                   Add a longitude offset (in degrees) to 
                                        the DEM.
  --y-offset arg (=0)                   Add a latitude offset (in degrees) to 
                                        the DEM.
  --z-offset arg (=0)                   Add a vertical offset (in meters) to 
                                        the DEM.
  --rotation-order arg (=xyz)           Set the order of an Euler angle 
                                        rotation applied to the 3D points prior
                                        to DEM rasterization.
  --phi-rotation arg (=0)               Set a rotation angle phi.
  --omega-rotation arg (=0)             Set a rotation angle omega.
  --kappa-rotation arg (=0)             Set a rotation angle kappa.

Projection options:
  --t_srs arg                           Specify the output projection as a GDAL
                                        projection string (WKT, GeoJSON, or 
                                        PROJ.4). If not provided, will be read 
                                        from the point cloud, if available.
  --t_projwin arg                       The output DEM will have corners with 
                                        these georeferenced coordinates. The 
                                        actual spatial extent (ground 
                                        footprint) is obtained by expanding 
                                        this box by half the grid size.
  -s [ --dem-spacing ] arg              Set output DEM resolution (in target 
                                        georeferenced units per pixel). These 
                                        units may be in degrees or meters, 
                                        depending on your projection. If not 
                                        specified, it will be computed 
                                        automatically (except for LAS and CSV 
                                        files). Multiple spacings can be set 
                                        (in quotes) to generate multiple output
                                        files. This is the same as the --tr 
                                        option.
  --tr arg                              This is identical to the --dem-spacing 
                                        option.
  --datum arg                           Set the datum. This will override the 
                                        datum from the input images and also 
                                        --t_srs, --semi-major-axis, and 
                                        --semi-minor-axis. Options: WGS_1984, 
                                        D_MOON (1,737,400 meters), D_MARS 
                                        (3,396,190 meters), MOLA (3,396,000 
                                        meters), NAD83, WGS72, and NAD27. Also 
                                        accepted: Earth (=WGS_1984), Mars 
                                        (=D_MARS), Moon (=D_MOON).
  -r [ --reference-spheroid ] arg       This is identical to the datum option.
  --semi-major-axis arg (=0)            Explicitly set the datum semi-major 
                                        axis in meters.
  --semi-minor-axis arg (=0)            Explicitly set the datum semi-minor 
                                        axis in meters.
  --sinusoidal                          Save using a sinusoidal projection.
  --mercator                            Save using a Mercator projection.
  --transverse-mercator                 Save using a transverse Mercator 
                                        projection.
  --orthographic                        Save using an orthographic projection.
  --stereographic                       Save using a stereographic projection. 
                                        See also --auto-proj-center.
  --oblique-stereographic               Save using an oblique stereographic 
                                        projection.
  --gnomonic                            Save using a gnomonic projection.
  --lambert-azimuthal                   Save using a Lambert azimuthal 
                                        projection.
  --utm arg                             Save using a UTM projection with the 
                                        given zone.
  --proj-lat arg (=0)                   The center of projection latitude (if 
                                        applicable).
  --proj-lon arg (=0)                   The center of projection longitude (if 
                                        applicable).
  --auto-proj-center                    Automatically compute the projection 
                                        center, when the projection is 
                                        stereographic, etc. Use the median 
                                        longitude and latitude of cloud points.
                                        This overrides the values of --proj-lon
                                        and --proj-lat.
  --proj-scale arg (=1)                 The projection scale (if applicable).
  --false-easting arg (=0)              The projection false easting (if 
                                        applicable).
  --false-northing arg (=0)             The projection false northing (if 
                                        applicable).

  --threads arg (=0)                    Select the number of threads to use for
                                        each process. If 0, use the value in 
                                        ~/.vwrc.
  --tile-size arg (=256 256)            Image tile size used for multi-threaded
                                        processing.
  --cache-size-mb arg (=1024)           Set the system cache size, in MB, for 
                                        each process.
  --no-bigtiff                          Tell GDAL to not create bigtiffs.
  --tif-compress arg (=LZW)             TIFF Compression method. [None, LZW, 
                                        Deflate, Packbits]
  -v [ --version ]                      Display the version of software.
  -h [ --help ]                         Display this help message.

**Your Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - ASP Version: [ASP 3.5.0-alpha]

**Additional context**

**Comment by rbeyer** [comment]
I think you have a typo, it needs to be `--stereographic` with two "e"s.

**Comment by skyrockets-21** [comment]
Please update the command in example: https://stereopipeline.readthedocs.io/en/stable/examples/lronac.html#running-stereo

point2dem--stereographic --auto-proj-center \
  --errorimage --orthoimage                 \
    run/run-PC.tif run/run-L.tif

**Comment by skyrockets-21** [comment]
> I think you have a typo, it needs to be `--stereographic` with two "e"s.

yes, thank you I spotted it too just now - the example itself on ASP website has typo. thank you @rbeyer

**Comment by skyrockets-21** [comment]
closing the issue - please update the documentation

**Comment by oleg-alexandrov** [comment]
That was a typo, and I put a fix. Thanks.
