### ISSUE TITLE
Do I need to do a new build for the camera to use parallel_stereo or other commands using data from LUTI, ShadowCam, Polcam?

### ISSUE THREAD

**Issue by Suwan0** [NeoGeographyToolkit/StereoPipeline#442]
Environment:
- ASP Version: 3.4.0
- ISIS3: Built from source
- OS: macOS

**Describe the solution you'd like**
I would like to know:
1. Whether ASP 3.4.0 supports KPLO LUTI camera models out of the box
2. If not, what steps are needed to add support for KPLO instruments (LUTI, ShadowCam, PolCam)
3. Whether a new build of ASP is required to process data from these instruments
4. Any specific configuration or settings needed in stereo.default for these cameras

**Describe alternatives you've considered**
- Successfully performed bundle adjustment using ISIS3's jigsaw
- Attempted to use stereo.default to force ISIS camera type
- Verified that ISIS3 correctly reads the camera model (campt and camrange, jigsaw and any other tools of ISIS3 work)
- Ensured all SPICE kernels are properly loaded

**Additional context**
The images process correctly in ISIS3, suggesting that the camera model and SPICE kernel setup is correct. The issue seems specific to ASP's camera model initialization. Any guidance on whether this requires additional build configuration or if there are plans to support these instruments would be greatly appreciated.

**Comment by oleg-alexandrov** [comment]
We did not work any explicit work to support  KPLO LUTI. If the images and cameras are packaged according to how ISIS expects it, it should work.

This also depends on if the left and right image have similar enough illumination. Particularly, not sure how ShadowCam will work out. 

If there is a problem, you can file a detailed report.
