### ISSUE TITLE
help understanding `bundle_adjust` ancillary products

### ISSUE THREAD

**Issue by steo85it** [NeoGeographyToolkit/StereoPipeline#444]
I have a quick question about `bundle_adjust` ancillary products. 

How/Why is it possible for the “heights_above_datum” of `{output-prefix}-mapproj_match_offsets.txt` to be different from the same column in the `{output-prefix}-final_residuals_pointmap.csv` file? I would have expected those to be equivalent/close to each other. 
In my specific case, the “heights_above_datum” from the `mapproj_match_offsets` are instead similar to the ones in the `initial_residuals_pointmap` (and similar to the initial DEM, when passing them through point2dem), while the `final_residuals_pointmap` has much lower “mean_residual” values (as expected) but the “triangulated DEM” looks very “different” (I would only expect a "rigid" transformation, but better/similar internal consistency, given the much lower residuals and the initial "decent" triangulations).

I attach here (from top left to bottom right): the "DEM" obtained by point2dem on the final_residuals_pointmap; the one from the initial_residuals_pointmap; the one from mapproj_match_offsets; the a priori DEM (the rotation between them should only be due to the reprojection inside point2dem).
![image](https://github.com/user-attachments/assets/05905a45-bdaf-47fa-b146-526627046014)

Thanks for any hints in better understanding these files!

**Comment by oleg-alexandrov** [comment]
The height of points in {output-prefix}-mapproj_match_offsets.txt is an honest height on the DEM surface, or close to it. The algorithm is as follows (also in the doc): rays are shot from individual matching pixels. Intersections with DEM surface are found. Those are averaged. So, it cannot stray too far from the DEM.

For the pointmap.csv file, each triangulated point need not be on the DEM at all. Its primary job is to be consistent with the pixels back in the cameras, so it is close to the intersection of rays from those matching pixels.

The --heights-from-dem option can pull this triangulated point somewhat vertically towards the DEM, for a very low value of --heights-from-dem-uncertainty it will likely force it to be very close. This assuming that the DEM is well-registered with the cameras.

The reason the initial_residuals_pointmap and mapproj_match_offsets heights are close, is because initial_residuals_pointmap is initialized based on the DEM, if a DEM is passed with --heights-from-dem, but then it is allowed to drift somewhat given the uncertainty and and the constraint that it care first about minimizing reprojection error. 

Does this make sense? Just how big is the discrepancy in your case?

**Comment by steo85it** [comment]
Oh ok, that makes sense, thanks! 
According to `geodiff`, after BA I have
```
Max difference:       27231.4 meters
Min difference:       3.86614e-07 meters
Mean difference:      72.7937 meters
StdDev of difference: 232.504 meters
Median difference:    38.9999 meters
```
the `initial` and `mapproj` geodiff residuals are very close to 0, which I now better understand with your explanation. My `--heights-from-dem-uncertainty` is set to 1 (meter).

> This assuming that the DEM is well-registered with the cameras.

I should probably iterate to register the bundle-adjusted images to the DEM before making further BA iterations, then. 
Also, this sentence in the manual:

> This is an advanced metric that is only helpful if the images and DEM are known to be very well-aligned, while the DEM is very accurate.

made me wonder if the mapproj_match_offsets percentile residuals can be trusted only if the images (and thus the final heights_above_datum) are well registered to the reference DEM (e.g., to rely on them to locate poorly aligned images to be removed for further BA rounds).

**Comment by oleg-alexandrov** [comment]
Yeah, mapproj_match_offsets.txt relies on all cameras and the DEM to be well-registered together. And yes, if say 90% of your images have low stats, and the rest have high stats, it means that those with high stats are junk. But if a lot of your images have high stats,  that means your registration is not good.

The stats per image are in mapproj_match_offset_stats.txt.

In my experience with LRO NAC, some images just could not be registered. Those images looked washed out and acquired at a very oblique angle, I think. But most of them do well.

**Comment by steo85it** [comment]
Yes, I usually remove any LRO NAC image with offnadir angle > 5 deg, to be on the safe side.

About the mapproj stats, most of the images have good ones (<1.5 meters when using 1 mpp mapproj images for BA), but even when "aggressively" cleaning up outliers (images with 2+ meters residuals, or even individual "connections" with residuals >2 meters), I still get regions with ghosting in my max-lit. 
I also tried making "partial max-lits" by splitting the available images in quartiles based on their residuals from `mapproj_match_offset_stats.txt`, hoping that at least the best (and optimistically the second best) max-lit would show no ghosting, but they ended up looking quite similar (overall good, but with localized ghostings from misaligned images). Which made me wonder if I could rely on those residuals at all, or if I was in a setting when they are unreliable (e.g., when not properly registered to the DEM). So, I get that's not so critical for using those values in the end, right?

**Comment by oleg-alexandrov** [comment]
>So, I get that's not so critical for using those values in the end, right?

No. The ultimate test is the lack of "ghosting", where apparently you have
problems.

I usually start with the images with the lowest mapproj stats, say the best
50 or so, and do the max-lit mosaic of those. If you still see
misregistration at that point, that means something is systematically bad.

A simple sanity check is to create a stereo terrain from a couple of those
bundle-adjusted images (with good convergence angle) and see if that
terrain has notable disagreements with your LOLA terrain (horizontally and
vertically). If yes, that means the alignment failed.

In the latest project I did I produced around 50 separate stereo DEMs from
pairs in the bundle-adjusted set, mosaicked them all, found the difference
from the mosaic to each, as sanity check, then aligned that one to LOLA and
applied the transforms to the cameras. (That still left around 5 m of
horizontal registration error, that needed finer-grained work.)

**Comment by oleg-alexandrov** [comment]
To add to previous:

> Yes, I usually remove any LRO NAC image with offnadir angle > 5 deg, to
be on the safe side.

that probably throws quite some good data, I'd guess. Anything with up to
20-30 degrees off-nadir should still be fine. In either case, throwing out
data later is better than earlier, as for bundle adjustment as a rule more
images is better even if not great ones, as then more likely tiepoints are
found.

**Comment by steo85it** [comment]
> that probably throws quite some good data, I'd guess. Anything with up to 20-30 degrees off-nadir should still be fine. 

you are right, but since at the lunar poles I usually have 1500+ images to "play with", a few off-nadir ones seemed more of a potential issue than a resource. In this case with fewer images though, I could relax that requirement.

> No. The ultimate test is the lack of "ghosting", where apparently you have problems.

I meant that the bad registration is not "critical" to using the residuals from the `mapproj_matches_offsets` file as reference to identify bad images. For sure I need to solve those ghostings before SfS. :) 
I'll try to be more granular by cross-checking with stereo DEMs, too, as you suggest. Thanks for all the explanations!

**Comment by oleg-alexandrov** [comment]
I ended up using around 1400 images. Kind of outrageous, yeah, but it was
hard to say ahead of time if registration will work with fewer. See how it
goes. Registration is grief.
