### ISSUE TITLE
Filter low-res disparity

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#62]
If low-res disparity has gross errors, it can make the run-time explode. Filtering is desired. 

Notes:

1. It would be nice to have a testcase.

2. Can the filtering function used in disparity post-processing be used? My impression was that it did not deal with outliers.

3. May need to filter disparity even later, such when going say from level 3 to level 2 in full-res calculation. It is at such a stage in case of snow images that more detail comes into view and the disparity can get seriously confused. 

4. May need hole-filling in addition to filtering at each step (save perhaps the last). After all, disparity is meant to be continuous. Hole-filling should be cheap at high levels of the pyramid.

5. Before doing any work it would be good to look at the literature.

**Comment by oleg-alexandrov** [comment]
A very low hanging fruit kind of fix here is the following. Each time a disparity is computed, say D_sub, or D itself at certain level on a certain tile, before it gets used further we should filter outliers from it. A very simple approach would be to keep only disparities within a factor of 3 of the 75-th percentile of disparity (with appropriate parameters added to stereo, documented, and noted in NEWS). This works very well for point2dem. Care should be used that when finding the 75-th percentile the work should be skipped if the vector is empty to avoid a segfault.

**Comment by ScottMcMichael** [comment]
Added a new option in commit 4f6e8bc7e0552a821f23c8f979880a01542ec396 to allow this.  The new filter is not safe to use as a default but it exists as an option for users to try out.

**Comment by oleg-alexandrov** [comment]
The description in the news is confusing though. It may make more sense to say "ability to filter out noisy disparities that greatly slow down run-time".
