### ISSUE TITLE
No-data values with ISIS images

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#64]
When pre-processing ISIS images, ASP has been for a long time setting pixel values below the smallest valid pixel value to this smallest valid pixel value. 

This is not the correct approach, those values need to be set to no-data. This however causes a lot of erosion when transforming images (e.g. homography alignment), as when an image is warped, interpolating at a location which has as a neighbor an invalid pixel results in an invalid value. 

That is to say, if the correct approach is implemented, users will suddenly start seeing DEMs with quite a bit of pixels missing at the borders of the valid region. The current incorrect approach has been in use for a long time without problems.

We need to decide at some point the trade-offs between fixing this or leaving it the way it is. This would require a good amount of experimentation.

**Comment by rbeyer** [comment]
This is super-old, and may no longer be something we're worried about, but the answer lies in the concept of multiple 'special pixels' that ISIS has.  In this case, when you compute a pixel value that is less than the allowed minimum, ISIS would consider that as a LRS pixel, not a Null (no-data) pixel.  Then when you're doing computations, you would then treat these LRS pixels differently than you would treat a Null pixel.  Specifically, when interpolating, treat them differently, and do something smarter.

However, treating them as the valid minimum pixel value is that smart thing, so I don't think the current approach (if, indeed, it is still current) is all that bad.
