### ISSUE TITLE
output from rpc_mapproject

### ISSUE THREAD

**Issue by SmithB** [NeoGeographyToolkit/StereoPipeline#70]
With ASP2.2, rpc_mapproject seems to try to write xml files in an unwritable location, and spews warning messages:

Warning: GdalIO: Unable to save auxilary information in /vsisubfile/3989_961434577,WV01_11DEC131600110-P1BS_R1C1-10200100150C8F00.ntf.aux.xml. (code = 1) 

[repeated ~ 10 times]
I've seen this problem on an RHEL6 linux box and on a mac running OSx 10.8

**Comment by oleg-alexandrov** [comment]
I re-opened this issue in the GDAL bug tracker. I can reproduce this only with gdal_translate.

**Comment by oleg-alexandrov** [comment]
This is something we can easily fix ourselves with a patch to GDAL. Should be a one-line change.

The reason this should be fix is because for large runs it can create hundreds of MB of log files.

This fix should be mentioned in NEWS, I think users will appreciate it.

**Comment by ScottMcMichael** [comment]
Warning suppressed by commit 2be619c987879a1a4b2b70604dde5ab05435b5ba

**Comment by oleg-alexandrov** [comment]
Looks to me like the wrong commit diff above.
