### ISSUE TITLE
stereo uses cached images even if input files changed.

### ISSUE THREAD

**Issue by zmoratto** [NeoGeographyToolkit/StereoPipeline#79]
Say someone creates map projected ISIS imagery and then runs stereo. Then they perform jigsaw and recreate their map projected ISIS imagery. Stereo will still load the previously created L and R tiffs that no longer represent the input imagery.

Can stereo instead keep track of the creation time or hash of it's input files to realize if it needs to rebuild its caches?

**Comment by oleg-alexandrov** [comment]
This should be looked into. A user just got bitten by it.

**Comment by ScottMcMichael** [comment]
Added check for this in 6f353d80d80a006135c37b11d626ff3639bb40df.
